CONTRIBUTING.md
DEVELOPER_GUIDE.md

correct anchor links in docs

---

AUTHORS.md

He had a lot to do with the FS2 work that happened (and is still ongoing).

Adding Michael Pilquist to contributors

---

ROADMAP.md

Organized into large features, and added plan implementation
and availability.

Update ROADMAP document.

---

README.md

add badges to our Readme now that we have Trave and CodeCov set up.

add Travis and CodeCov badges to Readme

---

.travis.yml

Figured it out for real this time. First issue was missing spaces in the command it seems. Then I realized we also needed to install jekyll among other things.

update travis.yml for publishMicrosite

---

modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
modules/api/functional_test/live_tests/recordsets/delete_recordset_test.py
modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
modules/api/src/it/resources/application.conf
modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneServiceIntegrationSpec.scala
modules/api/src/main/resources/reference.conf
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneRecordValidations.scala
modules/api/src/main/scala/vinyldns/api/repository/mysql/VinylDNSJDBC.scala
modules/api/src/test/resources/application.conf
modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala

2 things going on here 
1. Open up NS management to zone admins/ACL folks (remove the group check)
2. Add the approved server list check! not sure what happened to that, we were supposed to be validating NS servers on a list, but seems like weve been ignoring that

Fix NS management

---

modules/docs/src/main/resources/microsite/css/custom.css
modules/docs/src/main/resources/microsite/data/menu.yml
modules/docs/src/main/tut/portal/connect-to-zone.md
modules/docs/src/main/tut/portal/connections.md
modules/docs/src/main/tut/portal/zones.md

Minor changes for the PRs I merged in earlier today:
- Banner background changed to repeat and changed the fallback background color to a shade of blue from the banner.
- Changed "Understanding Connections" to "Understand Connections" so the text in the sidebar doesn't wrap when it's the selected page. I didn't want to make a css change to the side bar because that could become a slippery slope.

doc site tweaks [ci-skip]

---

DEVELOPER_GUIDE.md
README.md

Restructure existing Developer Guide information.

Developer Guide documentation

---

modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala

turn on coverage in batch validations file

---

CONTRIBUTING.md
DEVELOPER_GUIDE.md

Edits to the contributor and developer guides, specifically 
* More info on our issue templates
* More info on submitting PRs
* Moved testing info to the Developers Guide, and linked it in the Contributors Guide

contributing guide edits

---

AUTHORS.md
modules/portal/app/views/login.scala.html
modules/portal/app/views/main.scala.html

Added rel='noreferrer noopener' to links with target="_blank".

Fixed unsafe use of target="_blank"

---

modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeRepository.scala
modules/api/src/main/scala/vinyldns/api/domain/membership/GroupChangeRepository.scala
modules/api/src/main/scala/vinyldns/api/domain/membership/GroupRepository.scala
modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipRepository.scala
modules/api/src/main/scala/vinyldns/api/domain/membership/UserRepository.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordChangeRepository.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetRepository.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneChangeRepository.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/DataStore.scala
modules/api/src/main/scala/vinyldns/api/repository/DataStoreConfig.scala
modules/api/src/main/scala/vinyldns/api/repository/DataStoreLoader.scala
modules/api/src/main/scala/vinyldns/api/repository/DataStoreProvider.scala
modules/api/src/main/scala/vinyldns/api/repository/Repository.scala
modules/api/src/test/scala/vinyldns/api/repository/DataStoreLoaderSpec.scala
modules/api/src/test/scala/vinyldns/api/repository/MockDataStoreProvider.scala

splitting up https://github.com/vinyldns/vinyldns/pull/129 because its giant
This PR brings in the DataStoreProvider and related classes, though does not yet hook them into the application

Pluggable repos base classes

---

docker/api/docker.conf
docker/bind9/etc/named.conf.local
docker/bind9/zones/vinyldns.hosts
modules/api/functional_test/conftest.py
modules/api/functional_test/live_tests/zones/create_zone_test.py
modules/api/functional_test/utils.py
modules/api/functional_test/vinyldns_context.py
modules/api/src/it/scala/vinyldns/api/domain/dns/DnsConversionsIntegrationSpec.scala
modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneServiceIntegrationSpec.scala
modules/api/src/it/scala/vinyldns/api/engine/ZoneCommandHandlerIntegrationSpec.scala
modules/api/src/it/scala/vinyldns/api/repository/dynamodb/DynamoDBRecordChangeRepositoryIntegrationSpec.scala
modules/api/src/it/scala/vinyldns/api/repository/dynamodb/DynamoDBRecordSetRepositoryIntegrationSpec.scala
modules/api/src/it/scala/vinyldns/api/repository/dynamodb/DynamoDBZoneChangeRepositoryIntegrationSpec.scala
modules/api/src/main/resources/reference.conf
modules/api/src/main/scala/vinyldns/api/domain/dns/DnsConnection.scala
modules/api/src/main/scala/vinyldns/api/domain/dns/DnsConversions.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala
modules/api/src/test/scala/vinyldns/api/VinylDNSTestData.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/dns/DnsConnectionSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneViewLoaderSpec.scala
modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
modules/api/src/universal/conf/application.conf
modules/docs/src/main/tut/api/create-zone.md

Revert "Test DDNS connectivity when connecting to a zone"

---

modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/domain/auth/AuthPrincipalProvider.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala
modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
modules/api/src/main/scala/vinyldns/api/engine/sqs/SqsConnection.scala
modules/api/src/main/scala/vinyldns/api/repository/dynamodb/DynamoDBGroupChangeRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/dynamodb/DynamoDBGroupRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/dynamodb/DynamoDBHelper.scala
modules/api/src/main/scala/vinyldns/api/repository/dynamodb/DynamoDBMembershipRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/dynamodb/DynamoDBRecordChangeRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/dynamodb/DynamoDBRecordSetRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/dynamodb/DynamoDBUserRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/dynamodb/DynamoDBZoneChangeRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/mysql/JdbcBatchChangeRepository.scala
modules/api/src/main/scala/vinyldns/api/repository/mysql/JdbcZoneRepository.scala
modules/api/src/main/scala/vinyldns/api/route/VinylDNSAuthentication.scala
modules/api/src/main/scala/vinyldns/api/route/VinylDNSDirectives.scala
modules/api/src/test/scala/vinyldns/api/route/PrometheusRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/VinylDNSDirectivesSpec.scala
modules/core/src/main/scala/vinyldns/core/Instrumented.scala
modules/core/src/main/scala/vinyldns/core/route/Monitor.scala
modules/core/src/test/scala/vinyldns/core/route/MonitorSpec.scala
project/Dependencies.scala

part 2 of a few for externalizing the repos, they rely on this trait

move required monitor classes to core

---

MAINTAINERS.md
bin/release.sh
build.sbt
project/plugins.sbt
version.sbt

* update MAINTAINERS.md with info on release process
* add sbt release settings to build.sbt
* create bin/release.sh script

sbt release process

---

modules/api/src/main/scala/vinyldns/api/repository/ApiDataAccessor.scala
modules/api/src/main/scala/vinyldns/api/repository/ApiDataAccessorProvider.scala
modules/api/src/main/scala/vinyldns/api/repository/mysql/MySqlDataStoreProvider.scala
modules/api/src/test/scala/vinyldns/api/repository/ApiDataAccessorProviderSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/membership/UserChangeRepository.scala
modules/core/src/main/scala/vinyldns/core/repository/DataAccessor.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStore.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStoreConfig.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStoreLoader.scala
modules/core/src/main/scala/vinyldns/core/repository/Repository.scala
modules/core/src/test/scala/vinyldns/core/repository/DataStoreLoaderSpec.scala
modules/core/src/test/scala/vinyldns/core/repository/MockDataStoreProvider.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProvider.scala
modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProviderSpec.scala

Code is done i believe, just need to add more tests

Generic loader

---

build.sbt
modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInterfacesSpec.scala

forgot to clean this up in the last PR. we should only need dynamo dependency in the integration specs now

depend on dynamo only for IT

---

modules/api/src/test/scala/vinyldns/api/CatsHelpers.scala
modules/api/src/test/scala/vinyldns/api/ResultHelpers.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
project/Dependencies.scala

* Updated scalike to 3.3.1
* Updated play from 2.6.15 -> 2.6.19
* Updated akka-http from 10.1.3 -> 10.1.5
* Updated play-json from 2.1.9 -> 2.6.10
* Removed akka-remote dependency
Other changes:
* Renamed AkkaTestJawn -> ResultHelpers
* Removed the AkkaTestJawn (no longer used)

Updating some dependencies

---

modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBRecordChangeRepository.scala

Bug fix, Dynamo is complaining about this unused attribute on startup

remove change set status as attribute

---

modules/portal/app/views/groups/groups.scala.html
modules/portal/public/css/theme-overrides.css
modules/portal/public/lib/controllers/controller.groups.js

Add ability to update group information in the portal. Can update the name, group email and description. The functionality was already in the API so this is just a frontend portal implementation.
closes #171

update groups in the portal

---

.codecov.yml

this should report patch coverage, but always be green

ignore patch failures

---

AUTHORS.md

Due to to https://github.com/vinyldns/vinyldns-python/pull/17#issuecomment-431486438

Add Alejandro Guirao as a contributor

---

docker/api/docker.conf
docker/portal/application.conf
modules/api/src/main/resources/reference.conf
modules/api/src/universal/conf/application.conf
modules/docs/src/main/tut/operator/config-api.md
modules/mysql/src/it/resources/application.conf
modules/mysql/src/it/resources/logback.xml
modules/mysql/src/main/scala/vinyldns/mysql/MySqlConnectionConfig.scala
modules/mysql/src/main/scala/vinyldns/mysql/MySqlConnector.scala
modules/mysql/src/main/scala/vinyldns/mysql/MySqlDataSourceSettings.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlDataStoreProvider.scala
modules/mysql/src/test/resources/application.conf
modules/mysql/src/test/scala/vinyldns/mysql/MySqlConnectionConfigSpec.scala
modules/mysql/src/test/scala/vinyldns/mysql/repository/MySqlDataStoreProviderSpec.scala

made MySqlConnector with shared methods (will be used by the queue provider)

Common MySQL connector

---

modules/sqs/src/it/scala/vinyldns/sqs/queue/SqsMessageQueueIntegrationSpec.scala
modules/sqs/src/it/scala/vinyldns/sqs/queue/SqsMessageQueueProviderIntegrationSpec.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueProvider.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueSettings.scala
modules/sqs/src/test/resources/application.conf
modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageQueueProviderSpec.scala

Resolves #290.
- Implement `SqsMessageQueueProvider` implementation of `MessageQueueProvider`
- Slight refactor to config settings (`queue-url` → `queue-name`) and `SqsMessageQueue.apply`

SQS Message Queue Provider

---

.travis.yml

Do not merge!
Why:
- It doesn't seem like ruby is used anywhere
This change addresses the need by:
- :delete:
What side effects does this change have?:
- None, AFAIK
Fixes #223

Removes  unnecessary(?) ruby installations

---

modules/portal/public/lib/controllers/controller.zones.js

Fixes #131.
- add a check that doesn't resolve until the promise resolves

stop duplicate zone creation bug

---

modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/route/HealthCheckRouting.scala
modules/api/src/main/scala/vinyldns/api/route/HealthService.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BlueGreenRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/HealthCheckRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/HealthServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/PingRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/PrometheusRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/StatusRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/health/HealthCheck.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStore.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStoreLoader.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStoreProvider.scala
modules/core/src/main/scala/vinyldns/core/route/HealthCheck.scala
modules/core/src/test/scala/vinyldns/core/repository/MockDataStoreProvider.scala
modules/dynamodb/src/it/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProviderIntegrationSpec.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProvider.scala
modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProviderSpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/MySqlIntegrationSpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlDataStoreProviderIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlDataStoreProvider.scala
modules/mysql/src/test/scala/vinyldns/mysql/repository/MySqlDataStoreProviderSpec.scala

Fixes #313 
add dynamo/mysql database healthchecking

Add healthchecking dynamically for databases

---

docker/functest/run.sh

Fix Spacing in func test

---

modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala

Fixes #310
- move saveZoneProcess function back into saveTX

refactor to de-nest DB.localTx

---

modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/test/scala/vinyldns/api/engine/TestMessageQueue.scala
modules/core/src/main/scala/vinyldns/core/queue/MessageQueue.scala
modules/mysql/src/it/scala/vinyldns/mysql/queue/MySqlMessageQueueIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/queue/MySqlMessageQueue.scala
modules/sqs/src/it/scala/vinyldns/sqs/queue/SqsMessageQueueIntegrationSpec.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala

Fixes #313
- healthcheck mysql queue, SQS queue

Queue healthchecks

---

build.sbt
modules/portal/conf/application.conf
modules/portal/conf/reference.conf

fix portal configuration for local run

---

build.sbt

need this for the portal to be able to load mysql repos

portal rely on mysql

---

modules/api/src/test/scala/vinyldns/api/protobuf/ProtobufConversionsSpec.scala
modules/core/src/main/protobuf/VinylDNSProto.proto
modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
modules/mysql/src/it/scala/vinyldns/mysql/MySqlIntegrationSpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlUserChangeRepositoryIntegrationSpec.scala
modules/mysql/src/main/resources/db/migration/V3.9__UserChanges.sql
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlDataStoreProvider.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlUserChangeRepository.scala

Fixes #360.
- Update protocol buffer (protobuf).
- Implement MySQL user change repository.

Implement MySQL user change repository

---

MAINTAINERS.md
docker/docker-compose-build.yml
version.sbt

Release 0.8.0

---

modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/route/HealthCheckRouting.scala
modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
modules/api/src/test/scala/vinyldns/api/route/HealthCheckRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/health/HealthService.scala
modules/core/src/test/scala/vinyldns/core/health/HealthServiceSpec.scala
modules/portal/app/controllers/HealthController.scala
modules/portal/app/modules/VinylDNSModule.scala
modules/portal/conf/routes
modules/portal/test/controllers/HealthControllerSpec.scala
modules/portal/test/controllers/TestApplicationData.scala

portal health endpoint

---

modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBGroupRepository.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBHelper.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueProvider.scala

groups scan timing

---

modules/portal/app/controllers/LdapAuthenticator.scala
modules/portal/app/modules/VinylDNSModule.scala
modules/portal/conf/reference.conf
modules/portal/test/controllers/LdapAuthenticatorSpec.scala

Ldap healthcheck

---

modules/api/src/test/scala/vinyldns/api/repository/InMemoryBatchChangeRepository.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChange.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeSummary.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
modules/mysql/src/main/resources/db/migration/V3.10__BatchOwnerGroup.sql
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala

Fixes #341 
- add ownerGroupID field to batch
- store new field in database

Batch ownerGroupId

---

modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
modules/api/src/test/scala/vinyldns/api/protobuf/ProtobufConversionsSpec.scala
modules/core/src/main/protobuf/VinylDNSProto.proto
modules/core/src/main/scala/vinyldns/core/domain/membership/User.scala
modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
modules/dynamodb/src/it/scala/vinyldns/dynamodb/repository/DynamoDBUserRepositoryIntegrationSpec.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBUserRepository.scala
modules/portal/app/controllers/LdapAuthenticator.scala

Test flag on users

---

modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/protobuf/ProtobufConversionsSpec.scala
modules/core/src/main/protobuf/VinylDNSProto.proto
modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala
modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
modules/core/src/test/scala/vinyldns/core/domain/zone/ZoneSpec.scala

part of https://github.com/vinyldns/vinyldns/issues/364
adds the isTest field to the Zone type

add isTest field to zone

---

build.sbt
modules/api/src/test/scala/vinyldns/api/VinylDNSTestData.scala
modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/record/RecordSet.scala
modules/core/src/test/scala/vinyldns/core/TestMembershipData.scala
modules/core/src/test/scala/vinyldns/core/TestRecordSetData.scala
modules/core/src/test/scala/vinyldns/core/TestZoneData.scala
modules/core/src/test/scala/vinyldns/core/domain/record/RecordSetSpec.scala

Been slowly working on consolidating our test data in a reasonable way.
These files were heavily impacted by my next PR, but didnt want this changing around to result in impossible reviews, so this PR is just test cleanup

test data cleanup

---

modules/api/src/test/scala/vinyldns/api/GroupTestData.scala
modules/api/src/test/scala/vinyldns/api/domain/ReverseZoneHelpersSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/auth/MembershipAuthPrincipalProviderSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/VinylDNSAuthenticatorSpec.scala
modules/core/src/test/scala/vinyldns/core/TestMembershipData.scala

still working on cleaning/consolidating that test data. only a few more files with GroupTestData and then that can be removed

remove most GroupTestData usage

---

modules/api/functional_test/live_tests/recordsets/get_recordset_test.py
modules/api/functional_test/live_tests/shared_zone_test_context.py
modules/api/functional_test/utils.py
modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/AccessValidationsAlgebra.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetServiceAlgebra.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
modules/core/src/test/scala/vinyldns/core/TestMembershipData.scala
modules/core/src/test/scala/vinyldns/core/TestRecordSetData.scala
modules/core/src/test/scala/vinyldns/core/TestZoneData.scala

Fixes part of #350.
- only changes getRecordSet right now

include recordset ownergroup name in getRecordSet response

---

.travis.yml

Should bring this back as part of https://github.com/vinyldns/vinyldns/issues/321

dont test jdk11 until we need to

---

docker/bind9/etc/named.conf.local
docker/bind9/zones/dskey.example.com.hosts
docker/bind9/zones/example.com.hosts
modules/api/src/it/scala/vinyldns/api/domain/dns/DnsConversionsIntegrationSpec.scala
modules/api/src/main/scala/vinyldns/api/domain/dns/DnsConversions.scala
modules/api/src/test/scala/vinyldns/api/domain/dns/DnsConversionsSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/record/RecordData.scala
modules/core/src/main/scala/vinyldns/core/domain/record/RecordSet.scala
modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
modules/core/src/test/scala/vinyldns/core/TestRecordSetData.scala
modules/core/src/test/scala/vinyldns/core/domain/record/RecordDataSpec.scala

DS record support: DNS connection side

---

modules/api/functional_test/live_tests/recordsets/list_recordsets_test.py
modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/AccessValidationsAlgebra.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
modules/core/src/test/scala/vinyldns/core/TestRecordSetData.scala

Fixes #438.
- add ownerGroupName to getRecordsets response

add ownerGroupName to getRecordSets response

---

modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/protobuf/ProtobufConversionsSpec.scala
modules/core/src/main/protobuf/VinylDNSProto.proto
modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
modules/mysql/src/test/scala/vinyldns/mysql/repository/MySqlRecordSetRepositorySpec.scala

DS protobuf conversions

---

modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
modules/api/functional_test/live_tests/shared_zone_test_context.py
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/route/VinylDNSJsonProtocolSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/record/RecordData.scala
modules/core/src/test/scala/vinyldns/core/domain/record/RecordDataSpec.scala

should be 2nd to last PR; get that serialization!

DS routing/serialization

---

modules/portal/Gruntfile.js
modules/portal/app/views/main.scala.html
modules/portal/karma.conf.js
modules/portal/package.json
modules/portal/public/lib/controllers/controller.records.spec.js

Revert "Karma config updates"

---

modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
modules/api/functional_test/vinyldns_python.py
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/route/VinylDNSJsonProtocolSpec.scala
modules/portal/public/lib/services/records/service.records.js

Make DS records work

---

modules/portal/app/actions/ApiAction.scala
modules/portal/app/actions/FrontendAction.scala
modules/portal/app/actions/VinylDnsAction.scala
modules/portal/app/controllers/FrontendController.scala
modules/portal/app/views/batchChanges/batchChangeDetail.scala.html
modules/portal/app/views/batchChanges/batchChangeNew.scala.html
modules/portal/app/views/batchChanges/batchChanges.scala.html
modules/portal/app/views/groups/groupDetail.scala.html
modules/portal/app/views/groups/groups.scala.html
modules/portal/app/views/main.scala.html
modules/portal/app/views/noAccess.scala.html
modules/portal/conf/routes
modules/portal/public/css/vinyldns.css
modules/portal/test/controllers/FrontendControllerSpec.scala
modules/portal/test/controllers/VinylDNSSpec.scala

part of #445.
- create a dedicated view for locked out users
- add VinylDNS version to footer of all pages in the portal

portal improvements

---

modules/api/functional_test/live_tests/batch/get_batch_change_test.py
modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeServiceAlgebra.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChange.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeSummary.scala
modules/core/src/test/scala/vinyldns/core/domain/batch/BatchChangeSummarySpec.scala

Fixes #352.
- return owner group name in get batch endpoint
- return owner group name in list batch summaries

return owner group name in get and list batch

---

docker/docker-compose-build.yml
docker/docker-compose-func-test.yml
docker/docker-compose.yml

Updating to bind9 0.0.4 for new base debian image

---

modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
modules/portal/public/lib/controllers/controller.manageZones.js
modules/portal/public/lib/controllers/controller.records.js
modules/portal/public/lib/services/records/service.records.js

Adds portal modal and service support for DS records. Fixes #443.
- Add support for DS records in ACL rule modal
- Add conversion for DS record to display record in record set info

Portal support for DS records

---

modules/portal/conf/application.conf
modules/portal/conf/reference.conf

allows configuration at deploy time for the enabled repos

remove default repos from portal conf

---

modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlUserRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlUserRepository.scala

Fixes #496.
- Update SQL query for conditional building based on optional parameters
- Add integration tests

Update getUsers in MySQL user repository implementation to honor optional parameters

---

README.md
modules/docs/src/main/tut/tools.md

Documentation updates.
- add javascript as a supported language in the Readme
- move python from coming soon to the list of available tools
- add vinyldns-js to the list of available tools

update tooling/language lists

---

modules/portal/app/controllers/FrontendController.scala
modules/portal/app/controllers/OidcAuthenticator.scala
modules/portal/app/controllers/VinylDNS.scala
modules/portal/conf/routes
modules/portal/test/controllers/FrontendControllerSpec.scala

add more logging around oidc login

---

modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
modules/api/src/test/scala/vinyldns/api/repository/TestDataLoaderSpec.scala

followup to #499, the delete makes me nervous, adding one more layer of security there

Safer clean

---

modules/api/src/test/scala/vinyldns/api/protobuf/ProtobufConversionsSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/record/ChangeSet.scala
modules/core/src/main/scala/vinyldns/core/domain/record/RecordSetChange.scala
modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
modules/core/src/test/scala/vinyldns/core/domain/record/ChangeSetSpec.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBRecordChangeRepository.scala
modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBRecordChangeRepositorySpec.scala

helper on https://github.com/vinyldns/vinyldns/pull/501, we have a bunch of unused statuses. it's confusing :P

clean up statuses

---

modules/portal/app/controllers/VinylDNS.scala

we only log on login creates. moved to log for all new users

move log line for user create

---

modules/portal/app/controllers/VinylDNS.scala
modules/portal/app/views/setOidcSession.scala.html
modules/portal/conf/reference.conf
modules/portal/conf/routes
modules/portal/public/lib/oidc-finish.js
modules/portal/test/controllers/VinylDNSSpec.scala

OIDC safari fix

---

docker/bind9/zones/dummy.hosts
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneRecordValidations.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneRecordValidationsSpec.scala

- Filter zone record list for apex records only before checking against approved name server list.

fix zone connection validation

---

docker/api/docker.conf
modules/api/src/it/resources/application.conf
modules/api/src/main/resources/application.conf
modules/api/src/test/resources/application.conf
modules/api/src/test/scala/vinyldns/api/VinylDNSConfigSpec.scala
modules/api/src/universal/conf/application.conf
modules/docs/src/main/tut/operator/config-api.md
modules/docs/src/main/tut/operator/config-portal.md
modules/docs/src/main/tut/operator/setup-dynamodb.md
modules/docs/src/main/tut/operator/setup-mysql.md
modules/portal/conf/application-test.conf
modules/portal/conf/application.conf
modules/portal/conf/reference.conf

switching all the configs to be mysql for the user repo. this means our func tests and integration tests will run with that instead of dynamo

mysql user repo in tests

---

modules/docs/src/main/tut/portal/batch-changes.md

add ptr correspondence types to portal batch change docs

---

modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala

We don't allow creation of dotted hosts, but permit them to be synced in. This will help identify dotted hosts in the event we want to reach out to users in the future.
- Log dotted host records when zones sync
- this does not include apex records or SRV type records

log dotted records in zone sync

---

DEVELOPER_GUIDE.md

Fixes #332
- Note that we also have mysql and dynamodb module integration tests
- Note that there may be a delay needed between starting the docker containers and running the integration tests in the mysql module

add more info on integration testing

---

AUTHORS.md
modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
modules/docs/src/main/tut/api/get-zone.md
modules/docs/src/main/tut/api/list-zones.md
modules/docs/src/main/tut/api/zone-model.md

Fixes #260
- updated zone model to include the latest sync
- updated examples to include the latest sync

adding latest sync to api docs

---

docker/api/docker.conf
modules/api/functional_test/live_tests/zones/create_zone_test.py
modules/api/functional_test/live_tests/zones/update_zone_test.py
modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorIntegrationSpec.scala
modules/api/src/main/resources/application.conf
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala
modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/main/scala/vinyldns/api/route/StatusRouting.scala
modules/api/src/test/resources/application.conf
modules/api/src/test/scala/vinyldns/api/VinylDNSConfigSpec.scala
modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/protobuf/ProtobufConversionsSpec.scala
modules/api/src/test/scala/vinyldns/api/route/VinylDNSJsonProtocolSpec.scala
modules/api/src/universal/conf/application.conf
modules/core/src/main/protobuf/VinylDNSProto.proto
modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala
modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
modules/portal/public/lib/oidc-finish.js

alternate to https://github.com/vinyldns/vinyldns/pull/517

BackendID for connection info

---

AUTHORS.md

Fixes #.
- added my name to Authors.md

added myself as a contributor

---

modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala

dont love how the old way is queried, this should be more friendly

make logs on change more friendly

---

docker/api/docker.conf

Updating docker config values to deserialize `DnsBackend` values properly.

Update docker config values for DNS backend

---

modules/docs/src/main/tut/api/create-zone.md
modules/docs/src/main/tut/api/membership-model.md
modules/docs/src/main/tut/api/zone-model.md

update docs on test users

---

AUTHORS.md

At some point, we lost the sorting order in our authors list; bringing it back here.

Reorder AUTHORS.md

---

modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala

Fixes #553.
- save recordSet before setting recordSetChange to complete

save recordSet before completing recordSetChange

---

AUTHORS.md
modules/docs/src/main/tut/operator/config-api.md

Fixes #556 .
- Remove entry for record-set table from `config-api.md`

Remove recordset from dynamodb in the documents

---

docker/bind9/etc/named.conf.local
docker/bind9/zones/10.10.in-addr.arpa
modules/api/functional_test/live_tests/batch/create_batch_change_test.py
modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
modules/api/functional_test/live_tests/shared_zone_test_context.py
modules/api/functional_test/vinyldns_context.py

Updating references from old `30.172.in-addr.arpa` zone to `10.10.in-addr.arpa`.

Replace reverse IPv4 zone

---

modules/portal/app/views/main.scala.html
modules/portal/package.json

- update gentelella to use latest from Github
- inject oidc-finish script in html, this must've missed in a previous PR. caught when running `preparePortal`

Update Gentelella template

---

modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala

- Add a filter in getRecordSetsByFQDNs to only return recordsets in existing zones

Use getRecordSetsByFQDNs

---

modules/api/functional_test/live_tests/zones/list_zones_test.py
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneServiceAlgebra.scala
modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/zone/ListZonesResults.scala
modules/core/src/main/scala/vinyldns/core/domain/zone/ZoneRepository.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala

Fixes #.
- Change `startFrom` in `listZone` to `Option[String]`

Change paging to not use offset in MySqlZoneRepository

---

build.sbt
docker/api/Dockerfile

- Changes the docker base image to use alpine instead of debian

Changing base image to alpine

---

modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
modules/api/src/main/scala/vinyldns/api/domain/dns/DnsConversions.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/dns/DnsConversionsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/protobuf/ProtobufConversionsSpec.scala
modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
modules/api/src/test/scala/vinyldns/api/route/VinylDNSJsonProtocolSpec.scala
modules/core/src/main/protobuf/VinylDNSProto.proto
modules/core/src/main/scala/vinyldns/core/domain/record/RecordData.scala
modules/core/src/main/scala/vinyldns/core/domain/record/RecordSet.scala
modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
modules/core/src/test/scala/vinyldns/core/TestRecordSetData.scala
modules/core/src/test/scala/vinyldns/core/domain/record/RecordSetSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
modules/portal/public/lib/controllers/controller.manageZones.js
modules/portal/public/lib/controllers/controller.records.js
modules/portal/public/lib/services/records/service.records.js
modules/portal/public/templates/record-modal.html

Addition of support for the NAPTR RR Type
Clone of SRV support behaviour, adjusting as needed.
Room to improve validation, beyond my immediate abilities as a non-scala developer.

Adding NAPTR support

---

docker/bind9/zones/system-test.hosts
modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneRecordValidations.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneRecordValidationsSpec.scala

Ignored case for high value domain and name server regexes

case ignored regexes for high value domain and name servers

---

modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneChangeGenerator.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala
modules/docs/src/main/tut/api/membership-model.md
modules/docs/src/main/tut/api/zone-model.md

make zone isTest match user isTest

is test on zone create

---

modules/api/functional_test/live_tests/zones/get_zone_test.py
modules/api/functional_test/vinyldns_python.py
modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneServiceIntegrationSpec.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneServiceAlgebra.scala
modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
modules/portal/app/controllers/VinylDNS.scala
modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
modules/portal/app/views/zones/zones.scala.html
modules/portal/conf/routes
modules/portal/public/lib/controllers/controller.manageZones.js
modules/portal/public/lib/controllers/controller.manageZones.spec.js
modules/portal/public/lib/controllers/controller.zones.js
modules/portal/public/lib/controllers/controller.zones.spec.js
modules/portal/public/lib/services/zones/service.zones.js
modules/portal/public/lib/services/zones/service.zones.spec.js
modules/portal/public/mocks/mockZoneSubmit.json
modules/portal/public/templates/zoneconnection-modal.html
modules/portal/test/controllers/VinylDNSSpec.scala

taking over https://github.com/vinyldns/vinyldns/pull/595

Zone BackendID in portal

---

modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/auth/AuthPrincipal.scala

limit super user to normal access on record changes

---

modules/portal/Gruntfile.js
modules/portal/app/views/main.scala.html
modules/portal/karma.conf.js
modules/portal/package.json
modules/portal/public/lib/controllers/controller.records.spec.js

update JavaScript testing tools

---

modules/api/src/main/resources/reference.conf
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
modules/api/src/test/resources/application.conf
modules/api/src/test/scala/vinyldns/api/VinylDNSConfigSpec.scala
modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
modules/api/src/test/scala/vinyldns/api/engine/RecordSetChangeHandlerSpec.scala
modules/api/src/test/scala/vinyldns/api/repository/InMemoryBatchChangeRepository.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeRepository.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala

Fixes #.
- Load Notifiers from config
- Change updateSingleChanges to return the full BatchChange.
- Call Notifiers on successful BatchChange

Call Notifiers on BatchChange completion

---

modules/docs/src/main/tut/api/list-zone-changes.md

Fixes #654.
- add zoneId to list zone changes example

documentation: add zoneId to list zone changes example

---

docker/api/docker.conf
modules/api/src/it/resources/application.conf
modules/api/src/main/resources/application.conf
modules/api/src/test/resources/application.conf
modules/docs/src/main/tut/operator/config-api.md

- add `TXT` to shared-approved-types default value

update default shared-approved-types config

---

modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
modules/core/src/main/scala/vinyldns/core/health/HealthCheck.scala

* Cleaning up logging around sync to make it easier to query
* Added a log statement in the main health check to better inspect health check failures

Better sync logging

---

modules/docs/src/main/tut/api/batchchange-errors.md
modules/docs/src/main/tut/operator/config-api.md

docs for https://github.com/vinyldns/vinyldns/pull/677

Disable multi docs

---

modules/api/src/test/scala/vinyldns/api/repository/InMemoryBatchChangeRepository.scala

this was likely leftover from when we were in development on batch. no longer need this logger in whats basically a test mock

remove unnecessary logger

---

modules/docs/src/main/tut/api/recordset-model.md
modules/docs/src/main/tut/portal/manage-records.md

Fixes #600.
- add NAPTR record type as a supported record type in the docs
- add NAPTR attributes to the Record Data Information table in the docs

Naptr docs

---

docker/docker-compose.yml
modules/api/src/it/resources/application.conf
modules/api/src/it/scala/vinyldns/api/notifier/email/EmailNotifierIntegrationSpec.scala
modules/api/src/main/resources/reference.conf
modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifierConfig.scala
modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifierProvider.scala
modules/api/src/test/scala/vinyldns/api/notifier/email/EmailNotifierSpec.scala
project/Dependencies.scala

- Add email notifier
- Provide email on batch change to the requesting user

Add email notifier

---

bin/remove-vinyl-containers.sh
docker/docker-compose.yml
docker/email/.gitignore
modules/api/src/it/scala/vinyldns/api/notifier/email/EmailNotifierIntegrationSpec.scala

- Change directory for emails
- Update remove script to add mail container

Fix integration testing

---

modules/api/src/test/scala/vinyldns/api/repository/ApiDataAccessorProviderSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/membership/UserRepository.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStore.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStoreConfig.scala
modules/core/src/main/scala/vinyldns/core/task/TaskRepository.scala
modules/core/src/test/scala/vinyldns/core/repository/DataStoreLoaderSpec.scala
modules/dynamodb/src/it/resources/application.conf
modules/dynamodb/src/it/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProviderIntegrationSpec.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProvider.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBUserRepository.scala
modules/dynamodb/src/test/resources/application.conf
modules/dynamodb/src/test/scala/vinyldns/dynamodb/DynamoTestConfig.scala
modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProviderSpec.scala
modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBUserRepositorySpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/MySqlIntegrationSpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlTaskRepositoryIntegrationSpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlUserRepositoryIntegrationSpec.scala
modules/mysql/src/main/resources/db/migration/V3.15__Tasks.sql
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlDataStoreProvider.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlTaskRepository.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlUserRepository.scala

Precursor to #524.
- Create `task` repo in MySQL
- Create helper functions in `user` MySQL
- Deprecate DynamoDB `user` repo as unimplemented
- Update core and API modules with repo configurations

Repository preparation for LDAP sync

---

MAINTAINERS.md

Add notary key info to maintainer's guide

---

modules/api/functional_test/live_tests/zones/get_zone_test.py
modules/api/functional_test/live_tests/zones/list_zones_test.py
modules/api/functional_test/live_tests/zones/update_zone_test.py
modules/api/functional_test/vinyldns_python.py
modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/AccessValidationsAlgebra.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneServiceAlgebra.scala
modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/zone/ListZonesResults.scala
modules/core/src/main/scala/vinyldns/core/domain/zone/ZoneRepository.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
modules/portal/app/controllers/VinylDNS.scala
modules/portal/app/views/zones/zoneDetail.scala.html
modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
modules/portal/app/views/zones/zones.scala.html
modules/portal/conf/routes
modules/portal/public/css/vinyldns.css
modules/portal/public/lib/batch-change/batch-change.directive.js
modules/portal/public/lib/controllers/controller.zones.js
modules/portal/public/lib/controllers/controller.zones.spec.js
modules/portal/public/lib/services/zones/service.zones.js
modules/portal/public/lib/services/zones/service.zones.spec.js

With the addition of shared zones, some users are getting confused about what they should expect to see in the Zones section of VinylDNS. They also aren't sure how to know if a shared zone they want to work with exists in VinylDNS. Currently the "zones" API endpoint and Zones page in the portal only return zones a user is in the owner group for or has an ACL rule for. We return all zones to super and support users. We should make clear to users what zones they own but also allow them to see what zones exist in VinylDNS. This PR does not change their ability to access the specific zones though.
**API:**
- add `listAll` boolean parameter to the listZones API endpoint. Default is false. 
- update `canSeeZone` method in `AccessValidations.scala` to include shared …

Expand Zone access

---

MAINTAINERS.md

old key expires in august, added new one

add new notary key for nima

---

modules/api/src/it/scala/vinyldns/api/notifier/email/EmailNotifierIntegrationSpec.scala
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/domain/DomainValidationErrors.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInputSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala

split off of https://github.com/vinyldns/vinyldns/pull/706
save a batch that needs approval. will need minor updates (commented) when we have the right singleChange status options

Save a batch needing approval

---

modules/api/functional_test/live_tests/batch/approve_batch_change_test.py
modules/api/functional_test/vinyldns_python.py
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeServiceAlgebra.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala

Part of Batch Change Review Process (#659)
- add route for approving a pending batch change
- include basic validations that zone is pending and reviewer is authorized

add approve pending batch change route

---

modules/docs/src/main/resources/microsite/static/batch-csv-sample.csv

Fixes #726.
- include Add and Delete TXT examples

add TXT examples to batch CSV

---

modules/docs/src/main/tut/operator/config-portal.md
modules/docs/src/main/tut/operator/setup-ldap.md

- Add information and configuration example for locking users based on LDAP lookup

Add documentation for syncing users against LDAP

---

.travis.yml

- Adding Travis CI slack integration, with encrypted credentials.
- used the travis command line tool so it also cleaned up the formatting of our travis.yml file.

Add Travis CI Slack integration

---

modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/notifier/email/EmailNotifierSpec.scala
modules/core/src/main/protobuf/VinylDNSProto.proto
modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
modules/core/src/main/scala/vinyldns/core/domain/DomainValidationStoredError.scala
modules/core/src/main/scala/vinyldns/core/domain/SingleChangeError.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/SingleChange.scala
modules/core/src/main/scala/vinyldns/core/protobuf/BatchChangeProtobufConversions.scala
modules/core/src/test/scala/vinyldns/core/protobuf/BatchChangeProtobufConversionsSpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala

Just storage in this PR. Still todo in future PRs:
- Deal with response serialization (JsonProtocol)
- Bring in an actual soft failure

Store errors on single changes

---

modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala

because the beforeEach, we are resetting the route before every test. wondering if this is part of whats taking so much time

remove the val in the batch route test

---

bin/remove-vinyl-containers.sh
docker/docker-compose.yml
modules/api/src/it/scala/vinyldns/api/notifier/sns/SnsNotifierIntegrationSpec.scala
modules/api/src/main/resources/reference.conf
modules/api/src/main/scala/vinyldns/api/notifier/sns/SnsNotifier.scala
modules/api/src/main/scala/vinyldns/api/notifier/sns/SnsNotifierConfig.scala
modules/api/src/main/scala/vinyldns/api/notifier/sns/SnsNotifierProvider.scala
modules/api/src/test/scala/vinyldns/api/notifier/sns/SnsNotifierSpec.scala
project/Dependencies.scala

- Notify SNS topic on batch completion

Add SNS Notifier

---

docker/bind9/etc/named.conf.local
docker/bind9/zones/not.loaded.hosts
modules/api/functional_test/live_tests/batch/approve_batch_change_test.py
modules/api/functional_test/live_tests/batch/create_batch_change_test.py
modules/api/functional_test/live_tests/batch/reject_batch_change_test.py
modules/api/functional_test/live_tests/shared_zone_test_context.py
modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala

this PR will be mostly func tests

Zone discovery soft failure and tests

---

modules/api/functional_test/live_tests/batch/get_batch_change_test.py
modules/api/src/main/scala/vinyldns/api/notifier/sns/SnsNotifier.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala

look at the top of BatchChangeJsonProtocol. this isnt even used in our responses!

remove unused BatchChangeInfoSerializer

---

modules/api/src/it/scala/vinyldns/api/notifier/sns/SnsNotifierIntegrationSpec.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/notifier/sns/SnsNotifierSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala

part of #659 
- add needed fields to BatchChangeSerializer

Update batch change serializers

---

modules/portal/app/controllers/FrontendController.scala
modules/portal/app/models/Meta.scala
modules/portal/app/views/batchChanges/batchChangeDetail.scala.html
modules/portal/app/views/batchChanges/batchChangeNew.scala.html
modules/portal/app/views/batchChanges/batchChanges.scala.html
modules/portal/public/css/vinyldns.css
modules/portal/public/lib/batch-change/batch-change-detail.controller.js
modules/portal/public/lib/batch-change/batch-change-new.controller.js
modules/portal/public/lib/batch-change/batch-change.service.js
modules/portal/public/lib/batch-change/batch-changes.controller.js
modules/portal/public/lib/services/utility/service.utility.js
modules/portal/public/lib/services/utility/service.utility.spec.js
modules/portal/test/models/MetaSpec.scala

for #659, depends on new batch change statuses in  #768 and #771.
- add feature flags for manual batch review and scheduled batch change.
- add batch change data related to manual batch review to new batch change form and batch change detail views
- add batch change data related to scheduled batch changes to new batch change form, batch change detail and batch change summaries view
- change timestamps in batch change to display user's local time zone.
If a batch change that was in a pending state is approved, we will display the approval status in addition to the batch change status, since a batch change could be approved but it could still result in a Partial Failure or Failed during processing.

Add pending batch data in the portal

---

modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala

cleanup for #659 
- Update the pending count to include single changes with a status of "Pending" or "NeedsReview"

correctly get batchChangeSummary totalChanges

---

.travis.yml
build.sbt
modules/api/src/test/resources/application.conf
modules/portal/app/controllers/FrontendController.scala
modules/portal/app/controllers/VinylDNS.scala
modules/portal/app/modules/VinylDNSModule.scala
project/Dependencies.scala
project/build.properties
project/plugins.sbt

Updating play to 2.7

---

modules/portal/app/views/batchChanges/batchChangeNew.scala.html

- Update broken reference to sample CSV file

Fix link to sample CSV in DNS change screen

---

modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInputSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/notifier/email/EmailNotifierSpec.scala
modules/api/src/test/scala/vinyldns/api/notifier/sns/SnsNotifierSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/SingleChange.scala
modules/core/src/main/scala/vinyldns/core/protobuf/BatchChangeProtobufConversions.scala
modules/core/src/test/scala/vinyldns/core/protobuf/BatchChangeProtobufConversionsSpec.scala
modules/docs/src/main/tut/api/approve-batchchange.md
modules/docs/src/main/tut/api/batchchange-model.md
modules/docs/src/main/tut/api/create-batchchange.md
modules/docs/src/main/tut/api/get-batchchange.md
modules/docs/src/main/tut/api/reject-batchchange.md
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala

in preparation for SingleDeleteRecordChange

rename SingleDeleteChange to SingleDeleteRRSetChange 

---

modules/api/functional_test/live_tests/batch/approve_batch_change_test.py
modules/api/functional_test/live_tests/batch/cancel_batch_change_test.py
modules/api/functional_test/live_tests/batch/reject_batch_change_test.py
modules/api/functional_test/vinyldns_python.py
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeServiceAlgebra.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChange.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeSummary.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/SingleChange.scala
modules/core/src/main/scala/vinyldns/core/protobuf/BatchChangeProtobufConversions.scala
modules/core/src/test/scala/vinyldns/core/domain/batch/BatchChangeSpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
modules/mysql/src/main/resources/db/migration/V3.19__CancelledTimestamp.sql
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala

- Give creators of a batch change the ability to cancel the change if it's approval status is Pending Review

API: cancel batch change that is pending review

---

modules/portal/app/controllers/VinylDNS.scala
modules/portal/app/views/batchChanges/batchChangeDetail.scala.html
modules/portal/app/views/batchChanges/batchChanges.scala.html
modules/portal/conf/routes
modules/portal/public/lib/batch-change/batch-change-detail.controller.js
modules/portal/public/lib/batch-change/batch-change.service.js
modules/portal/public/lib/batch-change/batch-changes.controller.js
modules/portal/public/lib/directives/directives.modals.modal.js
modules/portal/public/templates/modal.html

Builds off #794 
- allow creator of a Batch/DNS Change to delete it in the portal

Portal cancel in review dns change

---

modules/portal/app/controllers/LdapAuthenticator.scala

add support user login in portal

---

modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
modules/docs/src/main/tut/api/batchchange-errors.md
modules/docs/src/main/tut/operator/config-api.md
modules/portal/public/lib/batch-change/batch-change-new.controller.js

- simplify the RecordRequiresManualReview error message
- add error and configuration to documentation

docs and updates for RecordRequiresManualReview

---

modules/api/functional_test/live_tests/batch/cancel_batch_change_test.py
modules/api/functional_test/live_tests/batch/create_batch_change_test.py
modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py

dont leave pending batches in pending state after tests complete

clean up after ourselves in the manual review tests

---

modules/portal/app/views/batchChanges/batchChangeNew.scala.html
modules/portal/public/lib/batch-change/batch-change-new.controller.js

No intermediate

---

modules/portal/public/lib/batch-change/batch-change.service.js
modules/portal/public/lib/services/profile/service.profile.js

- update the cancel batch change and regenerate credential requests to include a valid body

portal: update requests with no body

---

modules/api/functional_test/live_tests/batch/create_batch_change_test.py
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala

replaces #819, just handing minor comments

Refactor cvm

---

modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneServiceIntegrationSpec.scala
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/domain/access/AccessValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/access/AccessValidationsAlgebra.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
modules/api/src/test/scala/vinyldns/api/domain/access/AccessValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala

refactor/move in prep for global acl

create access package

---

modules/portal/app/views/batchChanges/batchChangeNew.scala.html
modules/portal/public/lib/batch-change/batch-change-new.controller.js
modules/portal/public/lib/batch-change/batch-change.spec.js

- add DeleteRecord change type in New DNS Change form, requires record data
- update CSV import function to accept DeleteRecord change type

support DeleteRecord in New DNS Change form

---

modules/docs/src/main/resources/microsite/static/dns-changes-csv-sample.csv
modules/docs/src/main/tut/api/batchchange-errors.md
modules/docs/src/main/tut/api/batchchange-model.md
modules/docs/src/main/tut/api/create-batchchange.md

Fixes #.
- add DeleteRecord info to the Batch Change model docs
- add DeleteRecord examples to the DNS Change CSV sample file

add DeleteRecord info to the docs

---

modules/api/functional_test/live_tests/batch/create_batch_change_test.py
modules/api/functional_test/utils.py
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInputSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
modules/docs/src/main/resources/microsite/static/dns-changes-csv-sample.csv
modules/docs/src/main/tut/api/batchchange-errors.md
modules/docs/src/main/tut/api/batchchange-model.md
modules/docs/src/main/tut/api/create-batchchange.md
modules/mysql/src/main/resources/db/migration/V3.20__SingleChangeExpandSingleChangeType.sql
modules/portal/app/views/batchChanges/batchChangeNew.scala.html
modules/portal/public/lib/batch-change/batch-change-new.controller.js
modules/portal/public/lib/batch-change/batch-change.spec.js

Need to table this for the time being

Revert multi-record feature

---

AUTHORS.md
modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
project/Dependencies.scala

Fixes #261.
Found the issue via Hacktoberfest!
- Update cats-effect to 2.0.0
- Update fs2 to 2.0.1

#261 Update cats-effect to 2.0.0 and fs2 to 2.0.1

---

bin/remove-vinyl-containers.sh

Adds the ldap docker container to the remove script

Add ldap to remove script [ci skip]

---

AUTHORS.md

Add Jon Moore to list of contributors.

---

docker/functest/run.sh
modules/api/functional_test/live_tests/batch/create_batch_change_test.py
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
modules/portal/app/models/Meta.scala
modules/portal/app/views/dnsChanges/dnsChangeNew.scala.html
modules/portal/test/models/MetaSpec.scala

- Remove multi-record feature flag from API/portal
- Update unit and functional tests
- Update functional test script

Remove multi-record feature flag from API and portal

---

modules/api/functional_test/live_tests/batch/create_batch_change_test.py
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeInterfaces.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
modules/core/src/main/scala/vinyldns/core/domain/SingleChangeError.scala
modules/core/src/main/scala/vinyldns/core/domain/batch/SingleChange.scala

Add record or zone contact information to User is Not Authorized error message in batch change/DNS Change.

make User Is Not Authorized error more informative

---

build/docker-release.sh

Update to allow tagging image with `latest`.

Update Docker release 

---

modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
modules/mysql/src/main/resources/db/migration/V3.21__RecordSetZoneIdNameTypeIndex.sql

- drop current zone_id_name_index from the recordset table because it is not unique
- add unique zone_id_name_type_index on the recordset table

add unique index on recordset

---

modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetServiceAlgebra.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala
modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneViewLoaderSpec.scala
modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
modules/core/src/main/scala/vinyldns/core/domain/record/ListRecordSetResults.scala
modules/core/src/main/scala/vinyldns/core/domain/record/RecordSetRepository.scala
modules/dynamodb/src/it/scala/vinyldns/dynamodb/repository/DynamoDBRecordSetRepositoryIntegrationSpec.scala
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBRecordSetRepository.scala
modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBRecordSetRepositorySpec.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
modules/portal/app/views/recordsets/recordSets.scala.html
modules/portal/public/lib/recordset/recordsets.controller.js
modules/portal/public/lib/services/records/service.records.js

- Support filtering list record sets by `recordOwnerGroupFilter`
- Update portal UI

Support record owner group filtering in record set search

---

docker/api/docker.conf
modules/api/src/it/resources/application.conf
modules/api/src/main/resources/application.conf
modules/api/src/test/resources/application.conf
modules/api/src/test/scala/vinyldns/api/VinylDNSConfigSpec.scala
modules/api/src/universal/conf/application.conf
modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBMembershipRepository.scala

- Use MySQL group change implementation

Use MySQL group change table

---

docker/api/docker.conf
modules/api/src/it/resources/application.conf
modules/api/src/main/resources/application.conf
modules/api/src/test/resources/application.conf
modules/api/src/test/scala/vinyldns/api/VinylDNSConfigSpec.scala
modules/api/src/universal/conf/application.conf

- Use MySQL zone change implementation

Use MySQL zone change table

---

docker/api/docker.conf
modules/api/src/it/resources/application.conf
modules/api/src/main/resources/application.conf
modules/api/src/test/resources/application.conf
modules/api/src/test/scala/vinyldns/api/VinylDNSConfigSpec.scala
modules/api/src/universal/conf/application.conf

Move final default repo (record-change) configuration to MYSQL instead of Dynamo

Use MYSQL record change table

---

modules/portal/app/views/main.scala.html
modules/portal/app/views/recordsets/recordSets.scala.html

Fixes #.
- main.scala.html
- recordSets.scala.html

change search icon to magnifying glass

---

ROADMAP.md
modules/docs/src/main/tut/operator/config-portal.md
modules/docs/src/main/tut/permissions.md

Put together a single place for all of the permissions settings available in VinylDNS.
Feedback welcome on this PR, will tune it as needed

Create Permissions Guide in Docs

---

bin/update-support-user.sh
docker/admin/Dockerfile
docker/admin/update-support-user.py

- Update usage to more clearly define params
- Fix error in help text re mysql port default
- Fix arg parsing in shell script
- Fix pulling latest proto regardless of local version
- Add clean up to docker run in shell script
- Remove unnecessary actions from Dockerfile

Update update-support-user.py script

---

docker/admin/update-support-user.py

WIP attempt to debug user support script

Attempt to fix user support script

---

.github/workflows/ci.yml
modules/docs/src/main/tut/faq.md

Adding a few changes to docs to see if publish site does indeed work

[ci skip] Adding a few touches to docs to test publish

---

build/docker/api/Dockerfile
build/docker/portal/Dockerfile

The default docker build was no longer running as setup.  Needed some small tweaks to the docker files to get it back building again.
Tested this locally and everything started up

[ci skip] Update docker build

---

modules/portal/app/views/groups/groupDetail.scala.html

Fixes #992.
-  Changed the input hint from "NT User Name" to "User Name".

Change input text hint for "add group member".

---

CONTRIBUTING.md

[ci skip] Update CONTRIBUTING.md to remove rfcs references

---

docker/api/docker.conf
docker/docker-compose-func-test-testbind9.yml
docker/docker-compose-func-test.yml
docker/docker-compose-quick-start.yml

Adds a route 53 configuration to the `docker.conf` for those interested in configuring route 53.

Add route53 provider to quick start

---

modules/r53/src/it/scala/vinyldns/route53/backend/Route53IntegrationSpec.scala
modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala
modules/r53/src/main/scala/vinyldns/route53/backend/Route53ProviderConfig.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueProvider.scala

Tickets: https://github.com/vinyldns/vinyldns/issues/1008
Fixes: #1008 
-
-

R53: Use DefaultAWSCredentialsProviderChain or StaticCredentialsProvider

---

.gitignore
modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
project/build.properties

Addresses #1010 
Attempt to fix sporadic build failures not resolving reference.conf

Remove lazy from config, update to sbt 1.4.0

---

modules/sqs/src/it/scala/vinyldns/sqs/queue/SqsMessageQueueProviderIntegrationSpec.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueProvider.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueSettings.scala

Tickets: https://github.com/vinyldns/vinyldns/issues/1008
Fixes: #1008 
-
-

Refactor SQS creds provider

---

modules/api/src/main/resources/reference.conf
modules/core/src/main/scala/vinyldns/core/domain/record/RecordData.scala
modules/r53/src/main/scala/vinyldns/route53/backend/Route53Conversions.scala

Fixes #1018 .
Also fixes a configuration merge bug now that access-key and secret-key are optional fields, this is non breaking since no one has x/x for their key/secret

R53 soa fix

---

.gitignore
build.sbt
modules/docs/src/main/resources/microsite/css/custom.css
modules/docs/src/main/resources/microsite/data/menu.yml
project/plugins.sbt

Had some side bar issues, the `menu.yml` was inadvertantly not merge because of .gitignore

[ci skip] Fixing menu for docs

---

project/Dependencies.scala

Update dnsjava dependency to 2.1.8

---

modules/api/functional_test/live_tests/batch/create_batch_change_test.py
modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
modules/api/src/test/scala/vinyldns/api/route/VinylDNSJsonProtocolSpec.scala
modules/core/src/main/scala/vinyldns/core/Messages.scala
modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
modules/portal/public/lib/dns-change/dns-change-new.controller.js

- Improved messages for some of the existing ones.
- Created an object Messages.scala in vinyldns.core which holds the new messages.
- Consolidated the new messages in an object so that they are easier to manage and can be pulled into configuration.

Improve messages

---

build/publish_docs.sh
modules/docs/src/main/mdoc/operator/setup-portal.md

Fix issue with `setup-portal.md`

Fix setup-portal docs

---

.github/workflows/publish-site.yml
CONTRIBUTING.md

Fix broken links in docs

---

project/Dependencies.scala
version.sbt

Drop Flyway dependency to `5.2.4`

Rollback Flyway dependency to support MySQL 5.x

---

quickstart/quickstart-vinyldns.sh

Update to quickstart script

---

.gitignore
build/sbt.sh
modules/api/src/it/scala/vinyldns/api/notifier/sns/SnsNotifierIntegrationSpec.scala
quickstart/.env
quickstart/docker-compose.yml
quickstart/quickstart-vinyldns.sh

- Add `debug` flag to `sbt.sh`
- Remove need for `LOCALSTACK_EXT_HOSTNAME` (provided by update to
backing Docker images)

Fix issues pertaining to running env

---

build/sbt.sh

- Allow ports to be exposed from command line
- Avoid errors on collision with existing exposed prots

Update sbt script to allow for debugging

---

.github/workflows/notify.yml
build/docker/api/Dockerfile
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlMembershipRepository.scala
test/api/functional/Dockerfile
version.sbt

- Fix issue with loading external JARs
- Bump version to 0.10.5

Update `Dockerfile` for API

---

modules/core/src/main/scala/vinyldns/core/domain/record/RecordSetDataRepository.scala
modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala

- Update for `recordset_data` table based on `rsdump` (Added record names to the record data.)

Update for recordset_data table based on rsdump

---

build/docker/api/logback.xml
build/docker/portal/logback.xml
modules/api/src/it/resources/logback-test.xml
modules/api/src/main/resources/logback.xml
modules/api/src/main/resources/test/logback.xml
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/backend/dns/DnsBackend.scala
modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
modules/api/src/test/resources/logback-test.xml
modules/api/src/universal/conf/logback.xml
modules/core/src/main/scala/vinyldns/core/domain/backend/BackendLoader.scala
modules/core/src/main/scala/vinyldns/core/queue/MessageQueueLoader.scala
modules/core/src/main/scala/vinyldns/core/repository/DataStoreLoader.scala
modules/core/src/test/resources/logback.xml
modules/mysql/src/main/scala/vinyldns/mysql/MySqlConnector.scala
modules/mysql/src/main/scala/vinyldns/mysql/queue/MySqlMessageQueueProvider.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlDataStoreProvider.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupChangeRepository.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlMembershipRepository.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlUserChangeRepository.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlUserRepository.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
modules/portal/conf/logback-test.xml
modules/portal/conf/logback.xml
modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala
modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueProvider.scala
project/Dependencies.scala

Fixes #1102 
- Change log levels based on the actual severity of the log message.
- Made changes to use ECS (Elastic Common Schema).

Update log levels and adopt ECS

---

modules/portal/app/views/recordsets/recordSets.scala.html
modules/portal/public/css/vinyldns.css
modules/portal/public/lib/recordset/recordsets.controller.js
modules/portal/public/lib/services/records/service.records.js

- Added `spinner` and `no records found` for Global recordset search.

Added spinner and no records found for recordset search

---

modules/api/src/main/scala/vinyldns/api/domain/DomainValidations.scala
modules/api/src/test/scala/vinyldns/api/domain/DomainValidationsSpec.scala

Fixes #1108 
- Updated the validation which now enables to perform Add, Delete for wildcard records.

Update validation for wildcard records

---

.gitignore
modules/mysql/src/main/resources/db/migration/V3.25__RecordSetBlobHash.sql
modules/mysql/src/main/resources/db/migration/V3.28__DropRecordSetBlobHash.sql
modules/mysql/src/main/resources/test/ddl.sql
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
modules/mysql/src/test/scala/vinyldns/mysql/repository/MySqlRecordSetRepositorySpec.scala
project/Dependencies.scala

- Dropped recordset BLOB `data_hash` column in `recordset` table, as its no longer use.

Dropped recordset BLOB hash column in recordset table

---

modules/docs/src/main/resources/microsite/static/dns-changes-csv-sample.csv

typo in documentation. exmaple.com to example.com

typo change

---

modules/mysql/src/main/scala/vinyldns/mysql/MySqlConnector.scala

- Add `envVars` configuration for flyway to enable environment variable configuration

Enable flyway configuration from environment

---

modules/portal/app/views/zones/zones.scala.html
modules/portal/public/lib/services/zones/service.zones.js

Fixes #1141.
- Added spinner in zone page for zone search.

Added spinner in zone search

---

modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala

Add Case Insensitivity to Group Search

---

modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala

Add Unit Tests For Zone Search Case Insensitivity

---

modules/api/src/main/resources/reference.conf
modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
modules/api/src/test/functional/tests/membership/list_my_groups_test.py
modules/api/src/test/functional/vinyldns_python.py
modules/portal/app/views/groups/groups.scala.html
modules/portal/app/views/zones/zones.scala.html
modules/portal/public/css/vinyldns.css
modules/portal/public/lib/controllers/controller.groups.js
modules/portal/public/lib/controllers/controller.groups.spec.js
modules/portal/public/lib/controllers/controller.zones.js
modules/portal/public/lib/controllers/controller.zones.spec.js
modules/portal/public/lib/services/groups/service.groups.js

Fixes #1137.
- Added pagination in `Groups` view similar to what we have in `Zones` view.

Add pagination in group view

---

modules/portal/app/controllers/VinylDNS.scala
modules/portal/app/views/zones/zoneDetail.scala.html
modules/portal/app/views/zones/zoneTabs/zoneChangeHistory.scala.html
modules/portal/conf/routes
modules/portal/public/lib/controllers/controller.manageZones.js
modules/portal/public/lib/controllers/controller.manageZones.spec.js
modules/portal/public/lib/services/profile/service.profile.js
modules/portal/public/lib/services/profile/service.profile.spec.js
modules/portal/public/lib/services/zones/service.zones.js
modules/portal/public/lib/services/zones/service.zones.spec.js
modules/portal/test/controllers/TestApplicationData.scala
modules/portal/test/controllers/VinylDNSSpec.scala

Fixes #1154.
- Added Zone history tab in zones page.

Add Zone history tab in zones page

---

AUTHORS.md

- Added @Jay07GIT, @Aravindh-Raju, @nspadaccino in Contributors list.

updated AUTHORS.md

---

DEVELOPER_GUIDE.md

- Update in DEVELOPER_GUIDE for run specific functional test cases.

updated DEVELOPER_GUIDE.md

---

modules/portal/public/lib/controllers/controller.groups.js

Fixes #1161.
- Fixed a bug for group details update. A super user can now edit group details (name, email and description) without being part of the group and without removing existing members of the group.

Resolve bug in group details update

---

modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
modules/portal/app/views/main.scala.html
modules/portal/app/views/zones/zones.scala.html
modules/portal/public/lib/controllers/controller.zones.js

Fixes #1188.
- Added autocomplete feature in zone search. Now we get zone suggestions as we type along with text-highlight.

Add zone autocomplete search

---

modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneSyncScheduleHandler.scala
modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneSyncScheduleHandlerSpec.scala
modules/portal/app/views/zones/zoneTabs/manageZone.scala.html

- Currently, the zone sync scheduler syncs zone at UTC timezone and also seems to auto sync multiple times. Provided information about UTC timezone in the portal, made minor changes to the scheduler and added log statement to debug the instances in this PR.

Debug zone sync scheduler issue

---

modules/portal/app/views/main.scala.html
modules/portal/public/lib/controllers/controller.zones.js

Fixes #1223.
- Fixes the styling of autocomplete search in zones and groups tab. Also, fixes a minor bug in zone autocomplete search.

Fix autocomplete search

---

modules/portal/app/views/zones/zoneTabs/zoneChangeHistory.scala.html
modules/portal/public/lib/controllers/controller.manageZones.js

Fixes #1225.
- Added the message `Group has been deleted now.` in the table to handle the error.

Fix zone change history bug

---

modules/api/src/main/resources/application.conf
modules/api/src/main/resources/reference.conf
modules/api/src/main/scala/vinyldns/api/Boot.scala
modules/api/src/main/scala/vinyldns/api/config/ValidEmailConfig.scala
modules/api/src/main/scala/vinyldns/api/config/VinylDNSConfig.scala
modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipProtocol.scala
modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
modules/api/src/test/functional/tests/membership/create_group_test.py
modules/api/src/test/resources/application.conf
modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
modules/core/src/main/scala/vinyldns/core/Messages.scala
modules/docs/src/main/mdoc/operator/config-api.md
version.sbt

Fixes https://github.com/vinyldns/vinyldns/issues/1208 
-We have added emailvalidation  for groups in the api side

group email validation code along with unit test

---

modules/portal/public/lib/controllers/controller.groups.js
modules/portal/public/lib/controllers/controller.manageZones.js
modules/portal/public/lib/controllers/controller.zones.js

- Replace `$log.log` with `$log.debug` and remove unwanted logs.

Update portal logs to debug level

---

modules/portal/public/lib/controllers/controller.manageZones.js

Fixes #1267.
- Fix bug with "Update Zone" button.

Fix zone button bug

---

modules/portal/public/lib/controllers/controller.zones.js

Fixes #1281.
- Ignore access value was changed to `true` in the PR: https://github.com/vinyldns/vinyldns/pull/1274 accidentally. Turned it back to `false`.

Fix 'My Zones' bug

---

modules/portal/public/lib/recordset/recordsets.controller.js

Fixes #1289.
- Fixed a bug with autocomplete search and resolved the error.

Resolve global recordset search autocomplete

---

modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html

Fixes #1297.
- collapse fix for manage records in zones view page.

collapse fix in manage records

---

modules/mysql/src/main/resources/db/migration/V3.30__AddStatusZoneAccess.sql

Update migration 3.30 to use drop foreign key instead of drop constraint

---

modules/docs/src/main/mdoc/api/get-user.md

Updated api docs for the [PR](https://github.com/vinyldns/vinyldns/pull/1328)
- updated get user api docs- added group id in user response.

Updated get user api docs

---

modules/docs/src/main/mdoc/faq.md

Fixes #1346.
- Added a FAQ regarding group change history being hidden for non-members of the group.

FAQ regarding group change history

---

modules/portal/app/views/zones/zones.scala.html
modules/portal/public/css/vinyldns.css
version.sbt

Fixes #1339.
- Alignment fix for abandoned zones.

Alignment fix for abandoned zones

---

.github/workflows/verify.yml

- Update codecov version to v4

Updated codecov version to latest v4

---

modules/portal/public/lib/recordset/recordsets.controller.js

Fixes #1350.
- Added a parameter to fix the pagination issue with record change history in portal.

Fix record change history pagination

---

AUTHORS.md
README.md

- Updated maintainers on README.md
- Updated contributors on AUTHORS.md

Updated maintainers and contributors

---

modules/docs/src/main/mdoc/operator/setup-ldap.md

Fixes #1362.
- Added details regarding java key store to the operators doc.

Add info regarding java key store

---

modules/portal/app/views/groups/groups.scala.html
modules/portal/public/lib/controllers/controller.groups.js

Fixes #1370.
- Update button when updating a group is disabled unless there's a change made.

Fix group update bug

---

modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
modules/portal/public/lib/services/records/service.records.js

Fixes #1378.
-Added spinner/loader for record data search in zone page.

spinner for record data search

---

.github/workflows/release-beta.yml

Add Beta Release Script

---

modules/portal/app/models/Meta.scala
modules/portal/conf/application.conf
modules/portal/test/models/MetaSpec.scala

Changes
- Added batch-change-limit params in portal config

added batch-change-limit params in portal config

---

modules/portal/public/lib/dns-change/dns-change.service.js

Fix
- Fix for dns edit page after submit.
Issue 
Spinner/ loader not closed properly when gets response

Fix for dns edit page after submit

---

.github/workflows/release-beta.yml
.github/workflows/release.yml

Update checkout from v2 -> v4
update login-action from v1 -> v3
update action-gh-release from v1 -> v2

Update Github actions plugins

---

modules/portal/app/views/dnsChanges/dnsChangeDetail.scala.html
modules/portal/public/css/vinyldns.css
modules/portal/public/lib/dns-change/dns-change-detail.controller.js

Fixes #1392 .
- Export CSV in batch changes

Export CSV in batch changes

---

modules/portal/public/lib/dns-change/dns-change-new.controller.js

Fixes #1394.
- Reset the batch file name when re-upload the same file with the changes again.

Reset the batch file name when re-upload the same file again

---

modules/portal/app/views/dnsChanges/dnsChangeDetail.scala.html
modules/portal/app/views/dnsChanges/dnsChanges.scala.html
modules/portal/app/views/groups/groupDetail.scala.html
modules/portal/app/views/zones/zoneDetail.scala.html
modules/portal/public/app.js
modules/portal/public/css/vinyldns.css
modules/portal/public/lib/controllers/controller.membership.js
modules/portal/public/lib/controllers/controller.records.js
modules/portal/public/lib/dns-change/dns-change-detail.controller.js
modules/portal/public/lib/dns-change/dns-change-new.controller.js
modules/portal/public/lib/dns-change/dns-changes.controller.js
modules/portal/public/lib/recordset/recordsets.controller.js
modules/portal/public/lib/services/utility/service.utility.js

Fixes #1395.
- Added icon to copy id's (group id, zone id, batch id) to clipboard
- Tooltips present in the portal were not working till now. Fixed that as well.

Copy group, batch and zone id to clipboard

---

modules/portal/public/lib/controllers/controller.records.js

- Fix for `undefined` recordSetGroupChange
Issue:
When user tries to `edit` or `request` ownership for existing record its showing recordSetGroupChange is undefined.
Steps to reproduce:
create shared zone from master repo( without ownership changes)
switch to ownership transfer pr.
Request ownership transfer.

Fix for undefined recordSetGroupChange

---

modules/portal/public/lib/controllers/controller.records.js

Fixes #.
- Fix for undefined issue in ownership transfer
-

fix for undefined issue in ownership transfer

---

modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifierConfig.scala
modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifierProvider.scala
modules/docs/src/main/mdoc/operator/config-api.md

Fixes #1419 .
- Updated email config with password authentication when smtp auth is enabled in config

Updated email config with password authentication
