- .travis.yml
- bin/func-test-api-travis.sh
- docker/docker-compose-build.yml
- docker/docker-compose-func-test.yml
- modules/api/functional_test/conftest.py
- modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
- `travis.yml`: Add `python` support,  removed non-existent `docker-compose` service and added functional test task.
- `func-test-api-travis.sh`: Create Travis-friendly version of `func-test-api.sh` with supported `docker-compose` parameters.
- `docker-compose-build.yml`/`docker-compose-func-test.yml`: Update MySQL port to `19001`
- `conftest.py`: Add DNS IP to logging
- `DnsJsonProtocol.scala`: Add back JSON validations prior to `scalaz` → `cats` conversion.
> Enable functional tests in Travis build

- .travis.yml
- build.sbt
- project/Dependencies.scala
- Consolidate verify step for API and portal to generate code coverage, removing deprecated `verify-api` and `verify-portal` `sbt` commands. Finish successful build by uploading to CodeCov.
- Add `47deg/Github4s` dependency and configure travis environment variable to publish Github pages on merge (see: https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html#publish-using-github4s).
Notes:
- I needed to create a personal token since we need to give Travis read/write repo access. There are currently two Travis builds that run - one from the organizational `vinyldns/vinyldns` repo, and one from the Travis CI checks. Once this gets merged, The simpler CI build will get removed (as it's a duplicate).
> Enable code coverage and gh-pages publish on merge to master

- .travis.yml
I looked at the sbt-microsites docs and the only difference i noticed between what they suggest and what we have set up is the value for micrositeGithubToken is `getEnvVar("GITHUB_TOKEN")`. We have `sys.env.get("GITHUB_TOKEN")`. So changing to match what they have. If that doesn't work we can dig deeper. for #73
> make publishing microsites work

- bin/generate-aes-256-hex-key.sh
- modules/api/src/main/resources/application.conf
- modules/core/src/main/scala/vinyldns/core/crypto/JavaCrypto.scala
- modules/core/src/test/scala/vinyldns/core/crypto/JavaCryptoSpec.scala
Implement a symmetric cryptography mechanism that uses AES-CBC padding with support for 256-bit keys, which doesn't double-encrypt or double-decrypt.
`JavaCrypto.scala` provides the implementation and `JavaCryptoSpec.scala` tests the functionality. `generate-aes-256-hex-key.sh` is a script that utilizes `openssl` to generate a 256-bit key that can be used with the cryptography mechanism.
Note for reviewers:
- To test this, I replaced updated the `crypto` object in `application.conf` to point to the new `JavaCrypto` mechanism with the appropriate key and ran unit and integration tests.
- Usage information will be added later in the operator guide.
> Implement JavaCrypto

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeInterfaces.scala
- modules/core/src/main/scala/vinyldns/core/crypto/NoOpCrypto.scala
- project/CompilerOptions.scala
The `NoOpCrypto` failed due to an unused `config` in the constructor. I left it there because the scaladoc for the class mentions it specifically. To fix I just added a `val` unless there is a more desired approach.
> add scalac option for fatal warnings (#24)

- modules/docs/src/main/tut/CNAME
previously added the domain for our doc site through GIthub settings and that make a CNAME file, but then it's deleted when running the publishMicrosite command, so needed to add the CNAME file in the docs module so it's included in publishMicrosite.
> add CNAME file to docs module

- build.sbt
Adding fatal warnings in this pr https://github.com/vinyldns/vinyldns/pull/90 caused errors when compiling scaladocs. Followed this thread to resolve the error: https://issues.scala-lang.org/browse/SI-9311. This is necessary because sbt docker builds scaladocs and will error out
> Suppress error thrown from scaladoc compilation 

- .travis.yml
Combining jobs to reduce the number of concurrent jobs from 5 to 2. This will allow us to run more builds in parallel.
> reduce travis jobs

- .travis.yml
- DEVELOPER_GUIDE.md
- README.md
- build.sbt
- modules/api/src/main/protobuf/VinylDNSProto.proto
- project/plugins.sbt
- project/protoc.sbt
The sbt protobuf plugin we were using forced developers to install
protoc version 2.6.1 on their local.  That makes it difficult
to onboard new developers.
sbt-protoc is an alternative plugin.  It has a lot of features we
are presently not using.  The biggest feature it brings is to
not require developers to install protoc.
* build.sbt - use the new protoc plugin
* VinylDNSProto.proto - add syntax = proto2 to ensure compile
to compatible protobuf version
* plugins.sbt - remove the old protobuf plugin
* protoc.sbt - add the new protoc plugin
> Update to sbt-protoc

- .travis.yml
Conditionally publish docs after the test stages pass.
- Only runs on the master build.
- Deploys the docs once (instead of once per job in the same stage).
I was hoping there was a way to also move the doc related installs to that stage also, but that doesn't seem possible. closes #73
> Travis configuration - conditionally deploy docs

- build.sbt
`bin/remove-vinyl-containers.sh`
`docker images`
`docker rmi -f` all images ids for the api
change version in build.sbt to 0.8.0
`sbt ";project api ;docker:publishLocal"`
This makes it so it doesnt pull the current 0.8.0 from docker hub and uses your local
run `bin/docker-up-vinyldns.sh`
repeat above but with this change
> change api docker entrypoint

- DEVELOPER_GUIDE.md
- README.md
- bin/docker-up-api-server.sh
- bin/docker-up-vinyldns.sh
- docker/functest/run.sh
`wget` is currently a VinylDNS installation dependency that is not available by default on Windows (and possibly other operating systems as well).
Note to reviewers: Tested both `docker-up-api-server.sh` and `docker-up-vinyldns.sh` locally.
> Replace wget with curl

- README.md
> update travis link in README

- modules/docs/src/main/tut/README.md
This should add the README to the root of the gh-pages branch after it's merged into master and the doc site is published to gh-pages. It will also be viewable at https://www.vinyldns.io/readme at that time although we aren't linking to it in the documentation site itself. closes #61
> add README to docs

- README.md
- bin/.env
- bin/docker-up-api-server.sh
- bin/docker-up-vinyldns.sh
- docker/.env
- docker/docker-compose-build.yml
- docker/docker-compose-func-test.yml
- docker/docker-compose.yml
- docker/portal/application.conf
Why I believe these changes are necessary: If I was someone not familiar with VinylDNS and was using the docker setup to play around, I am in a state of learning. I would want easier control over ENV values and explicit documentation. This allows me to then take the docker examples and set up my own production instance based on them without much headache and wasted time trying to infer things.
I have made multiple changes:
* Use of .env files (in docker/ and bin/), allowing customization for users.
* docker-compose files have been updated to use docker/.env values.
* Sourcing of .env in docker bash scripts.
* New example for disabling host filter in application.conf.
* README explaining it all.
I have tested all of these changes and it's working great.
> Docker Improvements

- modules/api/functional_test/live_tests/authentication_test.py
- modules/api/functional_test/live_tests/membership/list_group_members_test.py
- modules/api/src/it/scala/vinyldns/api/repository/mysql/JdbcZoneRepositoryIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
- modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
- modules/api/src/main/scala/vinyldns/api/route/MembershipJsonProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
- modules/api/src/main/scala/vinyldns/api/route/VinylDNSAuthentication.scala
- modules/api/src/main/scala/vinyldns/api/route/VinylDNSDirectives.scala
- modules/api/src/test/scala/vinyldns/api/GroupTestData.scala
- modules/api/src/test/scala/vinyldns/api/VinylDNSTestData.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/VinylDNSAuthenticatorSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/VinylDNSDirectivesSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/membership/User.scala
- modules/dynamodb/src/it/scala/vinyldns/dynamodb/repository/DynamoDBUserRepositoryIntegrationSpec.scala
- modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBUserRepository.scala
- modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBUserRepositorySpec.scala
This is part of #142 for the API side. Adds the "lockStatus" attribute to the the User class and database. The attribute is a custom type `LockStatus`, the value is either LockStatus.Locked or LockStatus.Unlocked.  Also adds a check of the attribute in the authentication.
> add locked account check to api authentication

- modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBUserRepository.scala
- modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBUserRepositorySpec.scala
The fromItem function was not checking for the possibility of
null when retrieving the LOCK_STATUS string.
Added that check, defaulting to null.  Added a unit test.
> Fix for null pointer in user deserialization

- build.sbt
**Background**
When the portal is packaged using the universal packager, it does not automatically pull in the dependencies and transitive dependencies of the `dependsOn` submodules.  This caused the portal to not start up when we deployed to our dev environment.
**Solution**
Seemingly, adding publish settings to `dynamodb` module in the portal project forced the dependencies to be present.
You can verify by running `stage` from the `portal` project in sbt.  Look in the `target` directory for the staged files.  Go to the `lib` directory, and you will now see the dynamodb submodule, along with the core submodule and aws-sdk jars.
> Fix portal build

- modules/api/src/main/resources/reference.conf
- modules/api/src/main/scala/vinyldns/api/repository/ApiDataAccessorProvider.scala
- modules/api/src/main/scala/vinyldns/api/repository/mysql/MySqlDataStoreProvider.scala
- modules/portal/app/controllers/UserAccountAccessor.scala
- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/app/modules/VinylDNSModule.scala
- modules/portal/conf/application.conf
- modules/portal/test/controllers/TestApplicationData.scala
- modules/portal/test/controllers/UserAccountAccessorSpec.scala
- modules/portal/test/controllers/VinylDNSSpec.scala
- project/Dependencies.scala
The root cause for the authentication error is that the portal
was not decrypting the user secret key before signing requests.
This is solved via the following:
1. Update VinylDNS controller to decrypt user secret when needed
1. Make sure that the `encrypt-user-secrets` feature flag is `on`
in the API reference.conf.  This was why in testing locally we
did not hit the same issue that we saw in the development environment.
Because the flag was false, test users secrets were not encrypted.
* `portal application.conf` - set the crypto to match the API
* `Dependencies.scala` - eliminate some duplication of dependencies
* `api reference.conf` - set the encrypt-user-secrets flag to true
* `TestApplicationData.scala` - modify the mock play app to have a
CryptoAlgebra binding
* `VinylDNS` - add …
> Fix authentication error in the portal

- modules/api/src/main/resources/reference.conf
- modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
- modules/api/src/main/scala/vinyldns/api/route/VinylDNSAuthentication.scala
- modules/api/src/test/scala/vinyldns/api/route/VinylDNSAuthenticatorSpec.scala
We should always assume encrypted user secrets at this point.
The feature flag was temporary.
> Kill with fire encrypt-secrets feature flag

- modules/portal/package.json
github it warning us that our npm bootstrap dependency has a vulnerability. Turns out the portal renders fine without it, but our javascript unit tests fail without it. Updated it to the version recommended by Github, 4.1.2
> update npm bootstrap due to vulnerability 

- docker/api/run.sh
- docker/functest/run.sh
There are transient failures in Docker where max retries (currently set to 30) are exceeded for MySQL, and then functional tests fail. Example build: https://travis-ci.org/vinyldns/vinyldns/jobs/431178316.
- Increase retries from 30 to 40
- Increase timeout duration of API start from 0.5 seconds to 1 second (to also match func test start)
> Increase MySQL retry count/sleep duration for API startup script

- .travis.yml
- modules/core/src/main/scala/vinyldns/core/queue/MessageQueueLoader.scala
- modules/core/src/main/scala/vinyldns/core/repository/DataStoreLoader.scala
- project/Dependencies.scala
- project/assembly.sbt
Fixes #271.
- Adds `openjdk11` in Travis build matrix.
- Rewrites the deprecated `klass.newInstance()` with `klass.getDeclaredConstructor().newInstance()`
- Adds the `jaxb` dependencies which had been removed from JDK since JDK 9.
- Updates `aws-sdk` and `sbt-assembly` to support JDK 11.
> Add JDK 11 support

- build.sbt
Fixes #209 .
- `modules/portal/conf/local.conf` is excluded from packaging so it doesn't show up in docker images
- `modules/portal/conf/local.conf` is excluded from `packageBin` so it doesn't show up in jars of the portal
To test: 
- have a `modules/portal/conf/local.conf` that overrides application.conf settings
- ensure that running the portal locally still has settings from local.conf
- run `sbt ";project portal;clean;docker:stage"`
- run `ls modules/portal/target/docker/stage/opt/docker/conf` and ensure `local.conf` is not there
- run `mkdir modules/portal/target/scala-2.12/test` and `cd modules/portal/target/scala-2.12/test && unzip ../portal_2.12-0.8.0-SNAPSHOT.jar && ls` and ensure `local.conf` is not in the jar
> exclude filter for local.conf

- modules/docs/src/main/tut/api/recordset-model.md
The record set model docs for SSHFP records cite a `typ` attribute. This is a typo and should be `type`.
Fixes issue #268
- correct SSHFP record set model documentation typo to read `type` rather than `typ`
- remove some whitespace
> fix typo re: SSHFP record model type attribute

- .codecov.yml
Codecov gets angry for any small fluctuation in coverage. this should allow a very minor drop.
> allow minor coverage drop

- build.sbt
- project/plugins.sbt
I added a feature to the sbt-microsites plugin that adds an edit button at the bottom of doc pages. https://github.com/47deg/sbt-microsites/pull/278. I think it will make it easier for folks to make doc contributions if they spot an issue while reading through.
- Upgrade sbt-microsites plugin to 0.7.24
- enable micrositeEditButton setting:
- Used "Improve this page" as the text
- the link goes to the edit view of a page, for example the Portal Guide page (https://www.vinyldns.io/portal/) will link to https://github.com/VinylDNS/vinyldns/edit/master/modules/docs/src/main/tut/portal/index.md
> add edit button to doc site

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
Closes #199
- remove recordIsUniqueInBatch validation from PTR record additions and updates in batch change. A PTR recordset can have multiple records.
- No change was actually needed in the portal since the validation happens in the API. Did verify through the portal though.
> allow multiple ptr records in batch change

- build.sbt
- project/Dependencies.scala
I believe this should get rid of the `Failed to load class "org.slf4j.impl.StaticLoggerBinder".` errors
For some reason the base sl4j import is still in apiDependencies, and other modules still seem able to import it. Mystery to me at the moment.
> move logging dependency to core

- docker/api/docker.conf
- modules/api/src/it/resources/application.conf
- modules/api/src/main/resources/application.conf
- modules/api/src/main/resources/reference.conf
- modules/api/src/universal/conf/application.conf
- modules/docs/src/main/tut/operator/config-api.md
related to https://github.com/vinyldns/vinyldns/pull/283
one of the mysql fields (connection-timeout-millis, idle-timeout, etc) was excluded from our deploy application.conf, but still being applied because in reference.conf.
took it out, should fall back to hikari defaults, not what we set
also updated docs
> remove config defaults

- docker/functest/run.sh
**Background**
The func test target is fixed to local docker compose and cannot be overridden.
**Solution**
Allow environment variables to be provided that override the target of the func tests so it can be run against any running instance.
> Adding environment variables to func test container

- docker/functest/run.sh
Some of our func tests are not meant to be run against "real" environments.  Since we now run the functest container against non docker environments, we have to skip these tests.
> Allow skipping of production tags from tests

- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala
- modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageQueueSpec.scala
Fixes #347.
- Add `MAXIMUM_BATCH_ENTRY_COUNT`
- Take lower of `MAXIMUM_BATCH_ENTRY_COUNT` and `maxMessageGroupCount` when partitioning batch change request into `SendMessageBatchRequest`
> Account for maximum batch entries in SQS SendMessageBatchRequest

- modules/api/src/main/scala/vinyldns/api/route/Aws4Authenticator.scala
- modules/api/src/test/scala/vinyldns/api/route/Aws4AuthenticatorSpec.scala
**Background**
In PostMan, we cannot send POST/PUT requests.  We see an error "Unable to validate signature".  The reason is because PostMan includes `Content-Length` header in the list of headers it uses to calculate the AWS Signature.  Unfortunately, we do not properly pull this header out when we do authentication, so the resulting signature VinylDNS calculates does not match what was sent by PostMan
**Steps to Replicate**
You can replicate against any real environment, but the easiest to debug is to spin up a local vinyldns api instance.
1. `sbt` from project folder
1. once sbt starts up, run `root/killDocker` just to make sure there are no stale containers
1. `project api` to switch to the api project
1. `dockerComposeUp` to start up our docker containers
1. `reStart` to start up the …
> Postman Fix, add content-length support

- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
- modules/portal/public/lib/controllers/controller.records.js
Need to wait for promises from multiple asynchronous calls to return before displaying records so that dotted host warning message does not erroneously appear.
Fixes #141.
- Update `controller.records.js` so that calls to `toDisplayRecord` wait for resolved zone and records promises.
- Update `batch-change-new-controller.js` and batch change view to remove unnecessary `event.preventDefault()` calls.
----
Note to reviewers: 
- Tested this by increasing the timeout of `loadZonesPromise = $timeout($scope.refreshZone, 0);` from `0` to `2000`.
- Information about the `$q` service/promise construction ca be found at: https://docs.angularjs.org/api/ng/service/$q
> Wait for zone and record set promises in portal before displaying record sets

- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueProvider.scala
Break out SQS settings logging so access and secret key aren't printed.
Fixes #381.
- Update logging message in `SqsMessageQueueProvider.scala`.
> Remove SQS access and secret key from logging

- .travis.yml
Noticed we're not caching maven dependencies, also, according to https://docs.travis-ci.com/user/caching/, npm should be cached this way instead of `node_modules`
> maven-cache

- modules/api/functional_test/live_tests/internal/status_test.py
- modules/api/functional_test/live_tests/zones/create_zone_test.py
- modules/api/functional_test/live_tests/zones/sync_zone_test.py
- modules/api/functional_test/live_tests/zones/update_zone_test.py
- modules/api/functional_test/utils.py
- modules/api/functional_test/vinyldns_python.py
Fixes #362
- removed `get_zone_history method` and `get_zone_change` methods
- update `wait_until_zone_change_status` method to check the status of the most recent zone change
> Remove zone history check

- modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
Fixes #390
- removed `zone.shared` from `def canSeeZone` in AccessValidations.scala
Looked like that was the only place it existed and wasn't included in tests
> remove existing shared zone logic

- modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorIntegrationSpec.scala
- modules/api/src/main/resources/reference.conf
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/dns/DnsConnection.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
- modules/docs/src/main/tut/operator/config-api.md
Add health check for DNS backend and tie into `Boot`.
Fixes #357.
- Split off IO component of `resolve` into `queryDnsBackend` (to avoid converting `IO` → `Result` → `IO` → `HealthCheck`)
- Create health check on `ZoneConnectionValidator` to test using the default zone connection info
> Add health check for DNS backend

- modules/api/functional_test/live_tests/zones/create_zone_test.py
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/protobuf/ProtobufConversionsSpec.scala
- modules/core/src/main/protobuf/VinylDNSProto.proto
- modules/core/src/main/scala/vinyldns/core/domain/auth/AuthPrincipal.scala
- modules/core/src/main/scala/vinyldns/core/domain/membership/User.scala
- modules/core/src/main/scala/vinyldns/core/protobuf/ProtobufConversions.scala
- modules/dynamodb/src/it/scala/vinyldns/dynamodb/repository/DynamoDBUserRepositoryIntegrationSpec.scala
- modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBUserRepository.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlUserRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
Fixes #368.
- add isSupport attribute to Users. Boolean like isSuper.
- Group services are set up a bit differently than Zones and records. For groups add the support check to view a group and also to list_my_groups so it returns all groups, like the behavior of a super user.
- For Zones and Records added support user to `canSeeZones`. Also added support user in `getPrioritizedAccessLevel` so their existing access rules will apply first but if they have no access rules then they'd get read access.
> Support admin

- modules/api/functional_test/live_tests/shared_zone_test_context.py
- modules/api/functional_test/live_tests/zone_history_context.py
- modules/api/functional_test/live_tests/zones/create_zone_test.py
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneValidations.scala
- modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/VinylDNSJsonProtocolSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala
Allow super users to create shared zones.
Fixes #345.
- Add `CreateZoneInput` class to restrict what is parsed into a zone creation request. Implement corresponding serializer and tie-in into routing.
- Add zone validation to check whether zone is shared, and if so, whether user is a super user.
- Updated existing create zone tests. Added new tests for shared flag.
> Allow super users to create shared zones

- modules/api/functional_test/live_tests/zones/sync_zone_test.py
- modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
- modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
- modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
Fixes #391.
- move the zone change handling for zone creates and syncs into the ZoneSyncHandler
> move zone change processing into zone sync handler

- README.md
`/dashboard` is for users that are part of the vinyldns team.
https://hub.docker.com/u/vinyldns will show everyone the list of repositories
Fixes #.
-
-
> Use correct docker hub URL

- modules/docs/src/main/tut/api/recordset-model.md
Fixes #377.
- Note that non-origin NS records can be created and deleted for approved name servers only. Link to information in the docs about approved name servers.
- Any non-origin NS record can be deleted.
- SOA and origin NS records are still read only.
> Ns record docs

- bin/docker-up-vinyldns.sh
- docker/.env
- docker/docker-compose-build.yml
- allows a user to purge vinyldns docker images used by `bin/docker-up-vinyldns.sh`
- allows a user to overwrite the version tag used by `bin/docker-up-vinyldns.sh`
> clean images and set version in bin/docker-up-vinyldns.sh

- modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
- modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
if a zone sync results in no changes in the zone, it will be stuck in syncing state. sad face.
> stuck syncing bug

- modules/docs/src/main/tut/operator/config-api.md
- modules/docs/src/main/tut/operator/pre.md
- modules/docs/src/main/tut/operator/setup-dynamodb.md
- modules/docs/src/main/tut/operator/setup-mysql.md
Add information regarding MySQL support and repository implementations.
Fixes #389.
- Provide information about MySQL support for queue and repositories
- Fix broken migration link
> Update MySQL information in operator guide documentation

- modules/portal/app/models/Meta.scala
- modules/portal/app/views/zones/zoneDetail.scala.html
- modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
- modules/portal/app/views/zones/zones.scala.html
- modules/portal/test/models/MetaSpec.scala
Fixes #349.
- add `shared_display_enabled` flag, to be set in the portal config, default is false
- display zone type as "Shared" or "Private" in the main Zones table in the portal and also the Manage Zone tab of an individual zone
To test locally: 
- add `shared_display_enabled = true` in portal module local.conf
> feature flag shared zone info

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/DomainValidationErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverterAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInterfacesSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/core/src/test/scala/vinyldns/core/TestZoneData.scala
- modules/docs/src/main/tut/api/batchchange-errors.md
PR 1 of 2. Fixes #342.
- Update JSON serializers/deserializers to accept/return owner group for batch change.
- Add group validation for:
1. valid owner group ID
2. owner group membership in batch service.
- Set owner group ID when applicable in batch change converter:
- For creates: if zone is shared and owner group ID is provided
- For updates: if zone is shared and existing record set doesn't have owner group ID set
- Add unit and functional tests
> Add owner group ID to batch change (without context validations)

- modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
- modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
- modules/api/functional_test/utils.py
- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidationsAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
Fixes #354.
- being in the ownerGroup only allows updates in a shared zone
- those with normal write, update, privileges can alter owner group id freely
- for non super users, the owner group must exist and the user must be in it
> ownergroup id logic for create and update recordset endpoints

- modules/api/functional_test/live_tests/recordsets/delete_recordset_test.py
- modules/api/functional_test/utils.py
- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidationsAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
Pre-req for #342.
- Update `deleteRecordSet` validation to pass in owner group ID
- Update tests
> Incorporate owner group validations into delete record set endpoint 

- modules/portal/Gruntfile.js
- modules/portal/app/views/main.scala.html
- modules/portal/karma.conf.js
- modules/portal/package.json
- modules/portal/public/lib/controllers/controller.records.spec.js
fixes #460 
Was working on some of the front end unit tests and realized PhantomJS doesn't support some functions we use like `find` that are part of ECMAScript2015 because it uses the IE browser https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility. A long rabbit hole later:
- I'm using ChromeHeadless instead of PhantomJS 
- had to rearrange the javascript files we pull in 
- had to downgrade the jquery version we use because the Gentellela template we use doesn't support the version we've been using. That weirdly only causes failures in tests 🤷🏽‍♀️ 
Testing steps:
1.  run `npm install`
2. run `grunt unit` from the `modules/portal` directory to run the unit tests
> Karma config updates

- modules/api/functional_test/live_tests/recordsets/delete_recordset_test.py
- modules/api/functional_test/live_tests/shared_zone_test_context.py
- modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
maintenance thing - because we are using the same ids always for the shared zones, one failed run can corrupt the database. pulled that out, just getting those zones by a list
> make shared zone ids unique across runs

- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
- modules/portal/public/lib/batch-change/batch-change.spec.js
Fixes #343 .
- add drop down menu in the batch change form to select the record owner group that will be applied to new and unowned records in shared zones 
- this is in the feature flag so `shared-display-enabled = true` should be added to local.conf or reference.conf to view
- we aren't adding an messaging around the field at this time, we'll do all the portal messaging in a separate issue/pr.
- batch change validations aren't merged in yet so the batch change will be accepted whether the owner group is set or not
> portal: add record owner group name to batch form

- modules/api/functional_test/live_tests/recordsets/delete_recordset_test.py
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/core/src/test/scala/vinyldns/core/TestRecordSetData.scala
Fixes #453.
- use canViewRecordSet validation instead of canSeeZone validation
- add unit tests in RecordSetServiceSpec
- ~~updated one func test to illustrate that a user in the record owner group of a record in a shared zone can view a related record set change. put that in a separate commit that doesn't need to be merged since i know @mitruly intends to test that in #454 https://github.com/vinyldns/vinyldns/pull/454/files#diff-8f6bb5f233fd1e5366e4831da659d5d8R727~~
- update `test_user_cannot_delete_record_with_write_txt_read_all` func test to confirm a user without admin rights can still get a record set change if they have other valid record access.
> Update getRecordSetChange access validation

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
- modules/api/functional_test/live_tests/recordsets/get_recordset_test.py
- modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidationsAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/DomainValidationErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/AccessValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
Fixes #342.
Add context validations for batch change. Branched off of #454 (from commit `c789fac`).
- Implement batch change validations
- Update access validations to accept requests when `ownerGroupId` is not defined in existing record set
- Added functional and unit tests
> Batch change owner group validations

- modules/portal/public/lib/batch-change/batch-change-new.controller.js
Fixes #481.
- correctly remove the ownerGroupId value in a new batch change. It was trying to send an empty attribute if a user selects a group then unselects a group, but we shouldn't send the attribute at all if the value is an empty string or doesn't exist.
> correctly clear ownerGroupId in new batch change form

- modules/portal/app/views/batchChanges/batchChangeDetail.scala.html
Fixes #356 .
This is currently branched off #459 
- display record owner group name below description in batch change details view
- if the group no longer exists display "Group deleted" with tooltip that includes the group ID at the time the group was set in the batch change.
Review notes:
- enable sharedDisplayEnabled in local.conf or reference.conf
> portal: add record owner group in batch changes detail view

- modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
- modules/portal/public/app.js
- modules/portal/public/lib/batch-change/batch-change.spec.js
- modules/portal/public/lib/constants.js
- modules/portal/public/lib/controllers/controller.records.js
- modules/portal/public/lib/controllers/controller.records.spec.js
- modules/portal/public/lib/services/records/service.records.js
- modules/portal/public/templates/record-modal.html
Fixes #468
- added a jsConfig value to hide the portal additions. since the modal file isn't scala it can't use the scala feature flag we set up.
- Adds record owner group selection in all of the record modals.
> portal: add record owner group to record modals

- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlUserRepository.scala
The logger for MySqlUserRepository referenced a different repository class.
- MySqlUserRepository logs as the correct class
> Fix MySqlUserRepository Logging

- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlUserRepositoryIntegrationSpec.scala
- in general sql collations are case insensitive by default
- mariadb and mysql 5.7 have the default `latin_swedish_ci`, in which the `ci` stands for `case insensitive` : https://mariadb.com/kb/en/library/setting-character-sets-and-collations/, https://dev.mysql.com/doc/refman/5.7/en/charset-applications.html
> add tests to make sure username search is case insensitive

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/live_tests/shared_zone_test_context.py
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
Fixes #480. Properly handle internal server error when PTRv4 zone discovery fails.
- Cover scenario where initial zone discovery finds potentially matching zones but fails on finding a record name match for IPv4 record
> Fix IPv4 PTR zone discovery

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/it/scala/vinyldns/api/domain/batch/BatchChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/main/resources/db/migration/V3.12__BatchChangeExpandInputName.sql
Expand `input_name` column from `VARCHAR(45)` to `VARCHAR(255)`. Fixes #462.
- Add migration script for `input_name` column expansion
- Add functional test for max label length creation in batch change
> Expand input_name column in single_change table

- modules/api/functional_test/live_tests/zones/delete_zone_test.py
- modules/api/functional_test/live_tests/zones/update_zone_test.py
- modules/api/functional_test/vinyldns_python.py
With a bit of latency in environments that are processing requests, it is possible to encounter a race condition when waiting for a zone create to finish. Resolves #515.
- Update `wait_until_zone_deleted` into a hard stopper by forcing assertions
- Update zone update/delete tests to wait for zone active status, rather than sync
> Fix wait condition for zone update/delete functional tests

- modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
- modules/api/src/test/scala/vinyldns/api/route/VinylDNSServiceSpec.scala
Fixes #281 .
- previously rejections were un logged, so something like an error from a non existent route or the user not providing a body in a post would be ignored by our logger
- logs method type (get, post, etc) and path for rejections
> log rejections

- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
- modules/portal/public/lib/batch-change/batch-change.spec.js
Fixes #510.
- Add "A+PTR" and "AAAA+PTR" record types in the new batch change form, "A+PTR" is now the default option, and "AAA+PTR" is second.
- On submit, re-format the batch change data to split the "A+PTR" or "AAAA+PTR" entries into two entries, one for the forward record and one for the reverse record.
Screenshot: new record types in record type menu
Screenshot: data entered in form for A+PTR record type
Screenshot: on submission attempt the entry is split into 2 entries, if there are any errors they appear on the relevant entry
Screenshot: batch change detail, shows the split forward and reverse records
Some testing suggestions:
Load zones: `1.9.e.f.c.c.7.2.9.6.d.f.ip6.arpa.`, `2.0.192.in-addr.arpa.`, and `ok.`
In a new batch change form:
"Add" "A+PTR" …
> portal ptr correspondence

- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
part of #346.
- add tooltips in New Batch Change form
- add link to create a group under the record owner group selection
> add help text to batch change form

- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
- modules/mysql/src/main/resources/db/migration/V3.13__RecordSetOwnerGroup.sql
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
Fixes #426 .
- Added a new alter query under migrations section
- Updated MySqlRecordSetRepository to include the optional new field `owner-group-id` 
- Integration tests
> Add ownerGroupId to mysql recordset table

- modules/api/functional_test/live_tests/batch/get_batch_change_test.py
- modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
- modules/api/functional_test/live_tests/zone_history_context.py
- modules/api/functional_test/live_tests/zones/sync_zone_test.py
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
- modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
- modules/api/src/test/scala/vinyldns/api/VinylDNSConfigSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
- modules/core/src/main/scala/vinyldns/core/domain/record/RecordSetRepository.scala
- modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBRecordSetRepository.scala
- modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBRecordSetRepositorySpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
Fixes #.
- check if ownerGroupId is not in any recordset before deleting group
> Delete group - Check if ownerGroupId is in any recordSet

- .travis.yml
- build.sbt
Pretty much ready to submit a pr with the scala js portal rewrite I've been working on. That branch is feature flagged and adds a `/v2` route to the existing portal when the flag is turned on
scala js has a known bug with 2.12.17 so want to get this first commit in first to make sure travis is good with 2.12.18
> upgrade to scala 2.12.18

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
right now recordsets are searched by zone id and recordset name, the getRecordSetsByFQDNs function will allow for batch gets using the input name that was directly input into the batch request
> batch change use getRecordSetsByFQDNs

- .travis.yml
additional tweak for #569.
- remove scala version 2.12.7 from travis.yml
> remove old scala version from travis

- docker/api/docker.conf
- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/resources/application.conf
- modules/api/src/main/resources/reference.conf
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/api/src/universal/conf/application.conf
- modules/docs/src/main/tut/api/create-batchchange.md
- modules/docs/src/main/tut/operator/config-api.md
- modules/portal/app/models/Meta.scala
- modules/portal/test/models/MetaSpec.scala
follow-up to #509.
now that we've migrated recordsets to mysql and get existing recordsets more efficiently we can increase the batch change limit.
- set default batch-change-limit to 1000
- remove tests that check for specific limit (every instance of VinylDNS doesn't have to have the same batch change limit!)
> increase batch change limit default to 1000

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
reverts part of #539
- use getRecordSetsByName instead of getRecordSetsByFQDNs
> use getRecordSetsByName

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
partial reversion of #539.
- remove the PTR records in the func test "test_create_batch_change_failed"
> remove PTRs from create batch func test

- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
Fixes #.
- Removed `DISTINCT` from GET_ZONES_BY_ADMIN_GROUP_ID
- Removed `DISTINCT` from BASE_ZONE_SEARCH_SQL
- Removed `DISTINCT` from GET_ZONE_ACCESS_BY_ADMIN_GROUP_ID
> Remove distinct from zone sql queries

- modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
- modules/api/src/main/scala/vinyldns/api/domain/dns/DnsConversions.scala
- modules/api/src/test/scala/vinyldns/api/domain/dns/DnsConversionsSpec.scala
Fixes #563.
- group TXT record data as a list of 255 character length strings
- also updated the `toDnsRRset` so it doesn't swallow errors
> correctly handle txt record data

- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala
- modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneViewLoaderSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
Fixes #581.
- Group logging into smaller chunks
- Move record drop logic from `ZoneSyncHandler` to `DnsZoneViewLoader` (prior to deserialization of `DNS.Record` type to VinylDNS' `RecordSet` model)
> Chunk up zone sync logging and drop records prior to deserialization into RecordSet model

- modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
- modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
- Allow dotted hosts for `TXT` records
- Update functional tests
> Allow dotted hosts for TXT records

- modules/api/functional_test/live_tests/zones/get_zone_test.py
- modules/api/functional_test/vinyldns_python.py
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
- modules/docs/src/main/resources/microsite/data/menu.yml
- modules/docs/src/main/tut/api/get-zone-by-id.md
- modules/docs/src/main/tut/api/get-zone-by-name.md
Fixes #.
- Added a route to `ZoneRouting` `GET /zones/name/<segment>`
- Added a new method to `ZoneService`to `getZonesByName`
- Unit and Integrations tests
- Functional tests
> Expose get zone by name route in the API

- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- modules/core/src/test/scala/vinyldns/core/TestMembershipData.scala
Currently, only super users can toggle the shared flag for zone creates/updates. We need more flexibility and don't want to open it up to all zone admins, so a middle ground is a zone admin that is also a support user.
- Enable functionality
- Create unit tests
> Enable shared zone toggle for zone admins that are also support users

- modules/api/functional_test/live_tests/zones/get_zone_test.py
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
tweak to #588
- make sure the given zone name is fully qualified (i.e. ends in  ".") before looking up the zone
> make sure zone name is fully qualified in getByZoneName

- modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
- modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
Fixes #.
- In the CommandHandler set the number of concurrent message batches as a parameter, default to 4 
- In the ComnandHandlerSpec test "main flow should process successfully" set the number of concurrent message batches to 1 to keep the test results consistent
> set default streams in mainFlow

- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/conf/routes
- modules/portal/test/controllers/TestApplicationData.scala
- modules/portal/test/controllers/VinylDNSSpec.scala
Supports #588
- add an API route in the portal for getZoneByName (`/api/zones/name/:name`)
> portal: add getZoneByName API route

- build.sbt
There is no trust data for "openjdk:8u201-jdk-alpine3.9" if you run `notary -s https://notary.docker.io -d ~/.docker/trust list docker.io/library/openjdk`, this causes docker to fail building the api and portal images when docker content trust is on, which is necessary for releases
> change openjdk version to one thats signed

- modules/api/functional_test/live_tests/zones/get_zone_test.py
In one of our functional tests, we check that the only backend ID returned is the test `func-test-backend` ID. The test needs to be more flexible so that loading more backend IDs should not fail this test.
> Update backend ID functional test to be more flexible

- modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneServiceIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
- modules/api/src/main/scala/vinyldns/api/engine/ZoneChangeHandler.scala
- modules/api/src/test/scala/vinyldns/api/engine/ZoneChangeHandlerSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
- modules/core/src/main/scala/vinyldns/core/domain/record/RecordSetRepository.scala
- modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBRecordSetRepository.scala
- modules/dynamodb/src/test/scala/vinyldns/dynamodb/repository/DynamoDBRecordSetRepositorySpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
When VinylDNS accepts a zone delete it removes the zone from the zone database but not the zone's recordsets from the recordset database. This orphans recordsets in the repo that turn into junk data. Even if someone reconnected to the zone the zone will have a new ID and duplicate all its recordsets in the recordset repo.
* Added logic to ZoneChangeHandler such that on a successful zone delete it will call a function to delete all recordsets with that zone id
* The ZoneChangeHandler will process the successful delete zone change even if the recordset delete fails
* Recordsets are NOT deleted from the DNS backend, just the recordsets table
> delete recordsets from repo on zone delete

- build.sbt
* Include `.csv` files as part of the ones to be included when building the site.
This is needed due to an [sbt-microsites setting](https://github.com/47deg/sbt-microsites/blob/0a8387363c2c87179c433ca406fd85d428ece6dc/src/main/scala/microsites/MicrositesPlugin.scala#L113) where only some extensions are included as part the built microsite.
> Include `*.csv` files in the built microsite

- modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
- modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
- modules/portal/app/views/zones/zones.scala.html
- modules/portal/public/css/vinyldns.css
- modules/portal/public/lib/controllers/controller.manageZones.js
- modules/portal/public/lib/controllers/controller.records.js
- modules/portal/public/lib/controllers/controller.records.spec.js
- modules/portal/public/lib/controllers/controller.zones.js
- modules/portal/public/lib/controllers/controller.zones.spec.js
Fixes #606.
- only show the Abandon zone button to zone admins (members of the group that owns the zone and super users)
- note: support users don't have the ability to change zones so shouldn't see the button
- renamed `isGroupMember` function to `canAccessGroup` that applies to zone admins, support users and super users. This is used to determine if the group name should be linked to in the Zones table.
- added `isZoneAdmin` function that applies to zone admins and super users. This is used to to determine if the Abandon zone button is visible.
> only show abandon zone button to zone admins

- bin/docker-up-api-server.sh
- bin/docker-up-vinyldns.sh
- docker/api/run.sh
- docker/functest/run.sh
- modules/api/src/universal/bin/wait-for-dependencies.sh
- modules/portal/dist/wait-for-dependencies.sh
Various shell scripts print "Retrying Again," when re-attempting some action.
The message can be rephrased to "Retrying" (or even "Trying Again")
to be more accurate and simple (and maybe a bit less like "ATM machine" ;) ).
> improve shell script language

- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
Fixes #614
- Group zones by ID instead of returning all zones to prevent duplicates
- Update spec to use `contain theSameElementsAs` instead of `contain allElementsOf` so duplicate zones in the response would fail
> group duplicate zones in listZones query

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/dns/DnsConversions.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/dns/DnsConversionsSpec.scala
Needs tests
the idea here is to open up zone discovery to be able to find zones for legal dotted hosts.
For now, just throwing all TXT records to this, but could be expanded to others if we decide thats the way to go.
> dotted host zone discovery in batch

- modules/portal/app/views/zones/zones.scala.html
Fixes #612.
- change message from "You have not connected to any zones." to "No zones found." in the Zones list table when the user has no zones and the zone load has completed.
> change no zones message

- modules/core/src/main/scala/vinyldns/core/notifier/AllNotifiers.scala
- modules/core/src/main/scala/vinyldns/core/notifier/Notification.scala
- modules/core/src/main/scala/vinyldns/core/notifier/Notifier.scala
- modules/core/src/main/scala/vinyldns/core/notifier/NotifierConfig.scala
- modules/core/src/main/scala/vinyldns/core/notifier/NotifierLoader.scala
- modules/core/src/main/scala/vinyldns/core/notifier/NotifierProvider.scala
- modules/core/src/test/scala/vinyldns/core/notifier/AllNotifiersSpec.scala
- modules/core/src/test/scala/vinyldns/core/notifier/NotifierLoaderSpec.scala
Add the Notifier trait and support for loading Notifiers from config
- Add Notifier trait
- Add Notification wrapper class
- Add NotifierConfig class
- Add NotifierProvider trait
- Add NotifierLoader object
- Add AllNotifiers wrapper for loaded Notifier instances
> Add Notifier to Vinyl core

- modules/portal/app/views/batchChanges/batchChangeDetail.scala.html
- modules/portal/app/views/groups/groups.scala.html
- modules/portal/app/views/zones/zoneTabs/changeHistory.scala.html
- modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
- modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
- modules/portal/app/views/zones/zones.scala.html
- modules/portal/public/css/vinyldns.css
fixes #477 
Issue:
Really long record data, record names, etc. in the Records table does not wrap and makes the table extend off the page.
Screenshots of current table:
- in the Records table in the portal added a class that sets the `word-break` to `break-all` so text can break between any characters (not just spaces and hyphens) to wrap onto multiple lines
Screenshots of portal with wrapping added:
> wrap text in the Records table

- modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
- modules/portal/app/views/zones/zones.scala.html
We said if we ever came up with a better name for the Zone shared attribute in the portal we would change it from Type. Today is that day! Going with "Access". The possible values remain the same as "Shared" or "Private".
> change Zone shared attribute label to Access

- .gitignore
- modules/api/functional_test/live_tests/recordsets/list_recordsets_test.py
- modules/api/functional_test/live_tests/zones/list_zones_test.py
- modules/api/src/main/scala/vinyldns/api/route/Aws4Authenticator.scala
- modules/docs/src/main/tut/api/list-recordsets.md
- modules/docs/src/main/tut/api/list-zones.md
- modules/docs/src/main/tut/getting-help.md
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
- modules/portal/.gitignore
Support wildcard searches for zones and record sets
* Updated MySqlRecordSetRepository to replace `*` with `%` for the `listRecordSets`
* Updated  MySqlZoneRepository to replace `*` with `%` for `listZones`
* Added integration tests to verify searches
* Updated api documentation to indicate wildcards are supported
* Fixed the `Aws4Authenticator`.  The main issue is how we are calculating the signature server side.  We are `urlDecoding` the query params _first_, and then calculate signature.  However, the way that it works on the client (verified in python and java) is that the query params are **url encoded** before signature calculation.  We may have other issues with query strings in the future.  In otherwords, the client says `recordNameFilter=%2Alist%2A` is signed, whereas on the …
> Wildcard search

- modules/api/functional_test/live_tests/zones/list_zones_test.py
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
Fixes #652.
- use the `ensureTrailingDot` DomainHelper method to add a trailing dot to the passed in name_filter if it doesn't have one
- all zones end in a trailing dot so this will have no impact on whether `*` are included for wildcard search or not.
> ensure trailing dot in list zones search

- modules/portal/app/controllers/FrontendController.scala
- modules/portal/app/views/main.scala.html
- modules/portal/test/controllers/FrontendControllerSpec.scala
with the addition of shared zones the expectation is majority of portal users will use the new batch change form rather than managing records in individual zones. This PR changes the default home page in the portal to the New Batch Change screen. Also changes the order of the navigation.
> Change homepage from Zones to New Batch Change

- modules/api/functional_test/live_tests/recordsets/list_recordsets_test.py
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
- modules/mysql/src/test/scala/vinyldns/mysql/repository/MySqlRecordSetRepositorySpec.scala
Fixes #565 .
* recordset paging is done by name and type
* paging will either match on `(name >= prev.name && type > prev.type) || (name > prev.name)`
* this is to address cases in which a page boundary record shares its name with other records that must still be paged
* in the previous logic, `name > prev.name`, duplicate records that were still not paged would be lost 
* in the new logic, a page will match for records with the previous last items name as long as the record does not have the same type
> mysql recordset fix paging for duplicate names

- modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/docs/src/main/tut/api/update-recordset.md
Fixes #638 
* If the recordSet zoneId and the zoneId in the route do not match return a 422
Can likely close #353
> Fail if zone id is not equal on recordset update

- modules/docs/src/main/tut/api/batchchange-errors.md
- modules/docs/src/main/tut/operator/config-api.md
Fixes #489.
- add error message information in batch change errors doc
- add example in api config docs
- noticed `shared-approved-types` was incorrectly nested in api config example so fixed that.
> add high value domain info to docs

- modules/docs/src/main/tut/portal/batch-changes.md
- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
- modules/portal/public/lib/batch-change/batch-change.directive.js
- modules/portal/public/lib/batch-change/batch-change.spec.js
I was relying on the checking the file content type to determine if an uploaded file was a CSV. Unfortunately "text/csv" is not the only content type that the file could be, there are many types so the check isn't reliable. 
This stackoverflow illustrates some of the options and issues people have come across https://stackoverflow.com/questions/7076042/what-mime-type-should-i-use-for-csv.
Instead changing it to reading the first line of the file and failing if it's not the header row we're expecting.
Also now there is only an import button and when the file is selected we immediately attempt to parse it. Either indicating the number of changes successfully imported or that the file was invalid.
> change batch change CSV validation

- modules/portal/app/models/Meta.scala
- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
- modules/portal/public/lib/batch-change/batch-change.spec.js
- modules/portal/test/models/MetaSpec.scala
builds on #670
- don't make TTL field required, but still validate minimum and maximum values if there's an input
- add tooltip indicating that the field is optional and what the system default is
- don't include the TTL value by default when adding rows, instead show the default value as placeholder text in the TTL field
> make batch change TTL optional in the portal

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/DomainValidationErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
in batch:
- disallow updates in batch that will update/delete an existing recordset with multiple recorddata fields
- disallow updates in batch that will create new recordsets with multiple recorddata fields
all of ^ config driven
> Config disabling of multirecord batch updates

- modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/ReverseZoneHelpersSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchTransformationsSpec.scala
bug fix.
in short, zone discovery for ipv4 relies on `endswith` to address delegated zone challenges. As a result, if you are looking for the zone for `1.2.3.0`, that will be transformed into a base of `3.2.1.in-addr.arpa.`, and we get all ending with that (so `3.2.1.in-addr.arpa.` and `0/30.3.2.1.in-addr.arpa.` (good), AND`13.2.1.in-addr.arpa.` (bad!))
this fixes that problem
> Reverse zone discovery bug

- modules/portal/app/controllers/LdapAuthenticator.scala
- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/test/controllers/LdapAuthenticatorSpec.scala
- modules/portal/test/controllers/TestApplicationData.scala
- modules/portal/test/controllers/VinylDNSSpec.scala
Our current LDAP authenticator and higher-level functions (eg. `authenticate` and `lookup`) return `UserDoesNotExistException` as a response when all domain authentications/look ups have been exhausted despite possible issues with the LDAP connectivity. This was fine before when we simply used LDAP authentication as a means to grant access to VinylDNS, but we need to clean up the logic if we are going to enable user locking.
- Limit the scenarios in which `UserDoesNotExistException` is returned to make sure that the user truly does not exist
> Fix LDAP lookup

- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
Fixes #79.
- add "Please contact <zone email> for access to the zone." to error message when a user tries to connect to a zone that already exists in VinylDNS.
I don't think we've used zone email for anything to this point, it's there so we should use it. If it's not as useful as the admin group name and admin group email we could change to that in the future, but this seems like it meets the objective of putting contact information in the message in the least complex manner.
> update 'Zone already exists' verbiage

- modules/docs/src/main/tut/api/get-batchchange.md
Fixes #263.
- correct the links in the documentation for `SingleAddChange` and `SingleDeleteChange`
> fix docs links for single changes

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/DomainValidationErrors.scala
- modules/docs/src/main/tut/api/batchchange-errors.md
Fixes #491.
- update message from `If zone exists, then it must be created in VinylDNS.` to `If zone exists, then it must be connected to in VinylDNS.`
> update ZoneDiscoveryError message

- modules/docs/src/main/resources/microsite/static/batch-csv-sample.csv
- modules/docs/src/main/tut/portal/batch-changes.md
- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- move the Batch Change CSV information to it's own section in the docs
- add info about the optional TTL field
- change the link text in the portal to "See documentation for sample CSV" and link to the Batch Change CSV section
> update docs and links for batch change csv import

- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
the original delimiter `....` has a bug on the edge case of an apex record since that will end in a dot, so the second half of the startFrom key that gets parsed would be `.<number>` which would turn into a number parsing error and be treated as no nextId
> make delimiter better

- modules/api/functional_test/live_tests/batch/reject_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/AccessValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeInterfaces.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/InMemoryBatchChangeRepository.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/auth/AuthPrincipal.scala
Rebased off #665 
- Adds validations to the reject batch change endpoint to check if a batch change is PendingReview and if the reviewer is a super user or support user
> validate batch change review rejection

- .travis.yml
- modules/api/src/main/resources/reference.conf
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala
- modules/api/src/main/scala/vinyldns/api/metrics/APIMetrics.scala
- modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
- modules/api/src/test/scala/vinyldns/api/metrics/APIMetricsSpec.scala
- modules/core/src/main/scala/vinyldns/core/Instrumented.scala
- project/Dependencies.scala
Adding updates to handle large zones (> 500,000).
1. `APIMetrics` allows configuration driven metrics collection.  Metrics we need here are for large zones, so we have a flag to enable logging of memory usage.  If `log-enabled=true` in the settings, start up a logging reporter that will memory usage to the log file every `log-seconds` seconds.
1. `CommandHandler` - increase the visibility timeout to 1 hour.  In testing with a large zone of 600,000 records, the initial zone sync process took 36 minutes.  Going to 1 hour should give us the ability to handle zones a little larger than 600,000 DNS records
1. `ZoneConnectionValidator` - increasing the timeout to 60 seconds from 6 seconds, as doing a zone transfer of large zones can take 10-20 seconds
1. `DNSZoneViewLoader` - adding logging …
> Large zone updates

- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
part of #660
- retrieve one more item than the given maxItems, use that to determine if there should be a nextID
> correct mysql listZones paging

- modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
- modules/portal/public/lib/controllers/controller.manageZones.js
- modules/portal/public/lib/controllers/controller.manageZones.spec.js
- modules/portal/public/lib/services/zones/service.zones.js
Fixes #698.
- change Access value in Manage Zone to be a drop down menu with Private and Shared. Default value is the zone's current shared value. false = Private, true = Shared.
- hide Abandon Zone button when confirming zone update. We already hide the Update Zone button at this point, just forgot to hide Abandon Zone as well in an earlier PR.
> update zone shared status in the portal

- modules/docs/src/main/tut/portal/manage-records.md
- modules/portal/public/lib/controllers/controller.manageZones.js
- modules/portal/public/lib/controllers/controller.records.js
The way we implemented SPF was not correct. Eventually, SPF will have to be implemented properly as a sub-type TXT record. For now remove support for creating new SPF records in the portal by removing the option from the record type menus in the portal. 
Leaving other references to SPF in the portal codebase for now so it doesn't interfere with any existing SPF records and in the event we repurpose that code when SPF is implemented properly.
> remove SPF record type from portal menus

- modules/api/functional_test/live_tests/zones/list_zones_test.py
- zones can vary in different environments so can't assume the count of zones when passing the listAll parameter
- verify listAll results in more zones than the test client has access to without listAll
- apply a name filter with the name of a test zone the user doesn't have access to and assert that it is in the results and the accessLevel is "NoAccess"
> adjust zone listAll func tests

- modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
- modules/api/functional_test/vinyldns_python.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/InMemoryBatchChangeRepository.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeRepository.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeSummary.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala
This is in support of implementing the batch change review process (#659).
Currently the `listBatchChange` is restricted to only showing the batch changes of the user making the request. We want to allow super and support users the ability to view all batch changes, regardless of user. 
- Add `listAll` Boolean parameter to the `listBatchChange` endpoint, default is false.
- If `'listAll` is set to true and the user is a super user or support user all batch changes in the system are returned (bearing in mind the current maxItems parameter, etc)
- if `listAll` is set to true but the user is not a super user or support user then only their batch changes will be returned.
> allow super and support users to list all batch changes

- modules/portal/app/views/login.scala.html
- modules/portal/app/views/main.scala.html
- modules/portal/app/views/setOidcSession.scala.html
- modules/portal/app/views/systemMessage.scala.html
Some users have reported seeing a prompt in Google Chrome to translate pages in Vinyl and appears to be detecting the page is in French. Specifically it's trying to translate the "Zones" menu label to "areas". I checked and all of our html tags already include `lang="en"` as recommended. But I've also read that Google may disregard that and have issues with language detection when there aren't a lot of words on the page. Depending on the amount of data a user has access to in Vinyl it seems the language detection might be off.
- Google recommends using this meta tag `<meta name="google" content="notranslate" />` to stop translation. Found here: https://support.google.com/webmasters/answer/79812?hl=en and in case the content on that page changes in the future, …
> add no translate meta tag

- build.sbt
- project/plugins.sbt
Fixes #655 .
`dockerUpdateLatest in api := true` does not scale to sub projects, the solution I found was to run `set every dockerUpdateLatest := true`
> update latest tag on release

- modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
- modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
- modules/api/functional_test/live_tests/zones/sync_zone_test.py
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
in the same vein as #702 we want to allow users to update existing recordsets with dotted hosts.
This pertains to the update recordset route.
- users can modify dotted host records with the following exceptions:
- users cannot create new dotted hosts (except TXT record types)
- users cannot change the name of a dotted host to another dotted host (except TXT record types)
> allow updates for dotted host records in update recordset

- modules/api/functional_test/live_tests/zones/list_zones_test.py
- modules/api/functional_test/vinyldns_python.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeSummary.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/ListZonesResults.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/ZoneRepository.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
- modules/portal/public/lib/controllers/controller.zones.spec.js
- modules/portal/public/lib/services/zones/service.zones.js
- modules/portal/public/lib/services/zones/service.zones.spec.js
Follow up to #689  and #700
- change "listAll" query parameter to "ignoreAccess" so it's more clear that the response will be zones or batch changes that are in the system regardless of the requesting user's access, _not_ a reflection of the quantity of results that are returned.
> change listAll query parameter to ignoreAccess

- modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
test-get-batch-record-owner-group is used in 2 tests
> remove duplicate group across func tests

- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
This is for the portal. If a user is only part of one group make that group the default selection in the new batch change form. Should help cut down on confusion over selecting an owner group when it's needed for record changes in shared zones.
> set default ownerGroup on batch change if user has only one group

- docker/bind9/zones/ok.hosts
- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/DomainValidationErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
VinylDNS doesn't allow the creation of dotted hosts, but legacy zones that are imported into Vinyl may have dotted hosts. We want to give users the ability to update or delete those existing dotted hosts. 
- affects batch change only.
- This only includes the following record types: A, AAAA, CNAME, MX (TXT was already allowed)
- Does not allowed creating new dotted hosts through batch change for any record type besides TXT
> Allow updating and deleting dotted host records in batch change

- modules/core/src/main/scala/vinyldns/core/task/TaskRepository.scala
- modules/core/src/main/scala/vinyldns/core/task/TaskScheduler.scala
- modules/core/src/test/scala/vinyldns/core/task/TaskSchedulerSpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlTaskRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlTaskRepository.scala
* `TaskRepository.claimTask` - modified to take a polling interval in addition to the task timeout
* `MySqlTaskRepository` - this is where the bug lies.  Before we were claiming the task if it WAS NOT in_flight and if the task had not expired.  This meant that every node if it started at a different time would run the task.  Changed the SQL so that we check if the task is NOT in_flight that it also hasn't been executed within the last pollingInterval.  *double check this guy*
* `TaskScheduler` - small fix to auto execute the task on task scheduler start up.  This is useful for tasks with long polling intervals.
> Fixing task scheduler running too often

- modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
- modules/api/functional_test/live_tests/zones/list_zones_test.py
- modules/api/functional_test/vinyldns_python.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/InMemoryBatchChangeRepository.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChange.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeRepository.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeSummary.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala
In support of #659 
- add `approvalStatus` query parameter on the list batch changes route to filter returned batch changes by their approval status. Parameter is available for any users.
- In conjunction with the `ignoreAccess` parameter this will allow super users to retrieve all batch changes in the system that are in a pending approval state.
> Add approvalStatus query param to list batch changes

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/DomainValidationErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/docs/src/main/tut/api/batchchange-errors.md
branched off of #702 
- create CnameAtApexError message and use it instead of RecordAlreadyExists error message when a CNAME record creation is attempted at a zone apex.
> Apex cname error message

- modules/core/src/main/scala/vinyldns/core/task/TaskScheduler.scala
- modules/core/src/test/scala/vinyldns/core/task/TaskSchedulerSpec.scala
- modules/portal/app/tasks/UserSyncTask.scala
The last fix improved the scheduling of tasks, but there is the possibility of a scheduled run to be missed.
We saw this running the user sync in dev every 1 hour:
1. Node 1 runs the task at 6:13:20, the task completes and the task completion time is updated to 6:13:50
2. Node 2 (on a different timer) attempts to run at 7:10:00 and notices it has only be 56:10 since the last run (less than one hour) and does not run it.
3. Node 1 attempts to run the task at 7:13:20, which is only 59:30 since the last run and does not run it.
The result is the "7 o'clock" execution time is skipped, as the task goes back to sleep for a full hour.
There are two problems:
1. We use `awakeEvery` instead of `fixedDelay`.  `awakeEvery` will try its best to wake up every hour, regardless of how long the tasks …
> Task Scheduler Fix

- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- modules/portal/public/css/vinyldns.css
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
With the implementation of shared zones some batch change requests require a record owner group. Users see the error message when relevant on the single line, but they still seem to be confused about how to resolve it, they aren't recognizing it's referring to the Record Owner Group field.
Some enhancements I want to try are highlighting the record owner group field if any of the changes error because there is no owner group and adding more messaging that the field is required.
> add errors to record owner group field

- docker/bind9/zones/ok.hosts
- modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
- modules/api/functional_test/live_tests/recordsets/list_recordsets_test.py
- modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
Addendum to #703
I missed allowing updates to CNAME dotted hosts in my previous PR.
- remove initial JSON validation that doesn't allow CNAMEs to contain a dot
- Pass existing recordset through the CNAME validations so we can compare the new and existing recordset names in the `isNotDotted` method.
> allow updates to dotted CNAME records

- modules/docs/src/main/tut/api/zone-model.md
- modules/docs/src/main/tut/operator/config-api.md
Fixes #623.
- add zone backend ID info to the zone model docs
- add zone backend ID info to the configuration example
> add backend ID info to docs

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
splitting up #748 into smaller PRs.
- in batch change routing turn the optional body on the reject batch change and approve batch change endpoints into instances of RejectBatchChangeInput and ApproveBatchChangeInput, respectively.
- We have to keep the entity as an option since it's only attribute is optional. Otherwise an `RequestEntityExpectedRejection` is raised.
> pass RejectBatchChangeInput and ApproveBatchChangeInput from routes

- modules/api/src/main/scala/vinyldns/api/domain/auth/AuthPrincipalProvider.scala
- modules/api/src/test/scala/vinyldns/api/domain/auth/MembershipAuthPrincipalProviderSpec.scala
split off #748 
In approveBatchChange, we will have the requesting userID, and the approver's authPrincipal.
But, we need the *requesting user* authPrincipal to flow back through the validations. To get that, need to be able to getAuthByUserId since thats the info we have
> add getAuthById to auth principal

- modules/api/functional_test/live_tests/batch/approve_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInputSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
more broken off of the approval flow
- get the requester associated with the change
- convert the change into a BatchChangeInput
after this, need to pass ^ through the validations
> Approval up front checks

- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
Ties in e-mail notifications into batch change rejection (for pending batch changes). Notifications are already triggered upon implementation by the `RecordSetChangeHandler`.
- Notify upon e-mail rejection
- Update e-mail content so that non-`AutoApproved` batch changes include review info.
> Batch change rejection email notifications

- modules/api/src/main/scala/vinyldns/api/Interfaces.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
worth a shot.
pulling from timeout in https://typelevel.org/cats-effect/datatypes/io.html#race-conditions--race--racepair
seems functionally pretty much the same, but wondering if removing an IO will help us with this test thats failing on timeout
> fix a test that travis hates

- modules/api/src/test/resources/application.conf
Akka HTTP's default value is `1.second`, which may not be sufficient for slower test environments under heavy load (https://doc.akka.io/docs/akka/current/testing.html#accounting-for-slow-test-systems):
>The tight timeouts you use during testing on your lightning-fast notebook will invariably lead to spurious test failures on the heavily loaded Jenkins server (or similar). To account for this situation, all maximum durations are internally scaled by a factor taken from the Configuration, akka.test.timefactor, which defaults to 1.
> Increase Akka test timefactor for route tests

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeReviewInfo.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
Note: this flow assumes that something happened outside the system (sync, zone create, etc) that makes the previously invalid change now invalid.
skipping checks because of approval (for something like lack or access) will come later when we need it
> the rest of the approval flow

- AUTHORS.md
- modules/docs/src/main/tut/tools.md
- Add `external-dns` as a new "integration" to the tools page. I didn't mention the vinyl integration specifically in the external-dns line, let me know if you think that is needed/would read better
> Add external-dns as an integration to Tools page

- modules/api/functional_test/live_tests/batch/get_batch_change_test.py
- modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
- modules/api/src/test/scala/vinyldns/api/repository/InMemoryBatchChangeRepository.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChange.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChangeSummary.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala
Part of #659 
- add batch change approval fields to batch change responses. Those fields are:
- approvalStatus
- reviewerId (optional)
- reviewerName (optional)
- reviewComment (optional)
- reviewTimestamp (optional)
These values will return for Get BatchChange requests and List Batch Change requests. Approve and Reject batch changes and Create Batch Change already return all of the above fields except reviewerName which is consistent with not returning ownerGroupName in those responses.
> add approval fields to batch responses

- modules/api/functional_test/live_tests/batch/approve_batch_change_test.py
- modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
- modules/api/functional_test/live_tests/batch/reject_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
- modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInputSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChange.scala
- modules/core/src/test/scala/vinyldns/core/domain/batch/BatchChangeSpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala
Part of #659 
- Instead of using the existing Pending and Failed statuses use PendingReview for a batch change in the pending state and use Rejected when a batch change is ManuallyRejected.
> expand batch change statuses

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
Add check to make sure that a scheduled change is not past due when approving.
* `BatchChangeErrors` - added `ScheduledChangeNotDue` error type that will be raised in the event someone approves a batch change (i.e. processes) a scheduled change too soon.
* `BatchChangeValidations` - added a `validateScheduledApproval` function that raises the `ScheduledChangeNotDue` if the scheduled date is not past due
* `BatchChangeRouting` - added `ScheduledChangeNotDue` to `handleErrors` to return a `Forbidden`
> Sched approval

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/live_tests/batch/reject_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
When we hit soft errors upon submitting a batch change request, this will most likely be due to a `ZoneDiscoveryError`. In the event that the zone is shared, `ownerGroupId` is required so we are trying to preemptively require the field.
- Add owner group ID check for batch changes that are manual review with soft errors
- Update tests
> Require owner group ID for soft errors

- modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
From a support perspective i find it annoying that I have to go to a zone to see an owner group or ACL group and then go to the Groups page to look up the group to see the members. Want to make the group names in the Manage Zones view link directly to the Group pages that list the members.
- Add a link under the admin group selection with a link to the current zone owner group
- Link the group name in ACL rules to the group page
> link to groups in the portal Manage Zone view

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/DomainValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/DomainValidationsSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/docs/src/main/tut/api/batchchange-errors.md
domains like `_jabber._tcp.gmail.com` are valid but would fail the batch change validations because it contains an underscore.
- relax the `validFQDNRegex` by including underscores
- update the `InvalidDomainName` error message to include underscores as valid characters
> allow underscores in batch change requests

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeErrors.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
For scheduled changes we don't want users setting a time in the past.
- if scheduled changes are enabled check that the scheduled time is after the current time
I went the current time, but we could easily change it to an hour from the current time or some other set time from the current time.
> validate scheduled time is in the future

- docker/api/docker.conf
- docker/bind9/zones/1.9.e.f.c.c.7.2.9.6.d.f.ip6.arpa
- docker/bind9/zones/2.0.192.in-addr.arpa
- modules/api/functional_test/live_tests/batch/approve_batch_change_test.py
- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/resources/application.conf
- modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneRecordValidations.scala
- modules/api/src/test/resources/application.conf
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/core/src/main/scala/vinyldns/core/domain/SingleChangeError.scala
Similar to existing high-value domains where we disallow certain records from being created via configuration, domains requiring manual review is a configured list that requires manual review (via batch interface) for the change to process. This PR takes care of only the batch interface process flow, with the record set restriction being handled separately.
- Add configuration (`manual-review-domains`) for changes that will automatically be flagged as non-fatal errors. If manual review is disabled, this will manifest as fatal errors. If manual review is enabled, these will be handled normally.
- Add tests
> Implement domains requiring manual review (via batch change interface)

- modules/api/functional_test/live_tests/batch/list_batch_change_summaries_test.py
- add the `@pytest.mark.manual_batch_review` flag to a func test that depends on manual batch change review being enabled.
> flag func test

- build.sbt
- project/plugins.sbt
There was an issue starting the docker containers due to how native packager
works where we were seeing issues with the container being able to start.
The issue was that we were assuming a "daemon" user to run the containers under.
At some point this changed to "1001:0".  As a result, there were not sufficient
privileges to start the containers because the "daemon" user was invalid or did
not have access to the scripts created by sbt native packager.
* `build.sbt` - update the user to "1001:0" for our custom install.  Cleaned up the hardcoded references in the script extras to `/opt/docker` to use the variable `app_home` instead.
* `plugins.sbt` - updated to the latest sbt native packager
> Fix docker releases

- modules/docs/src/main/tut/portal/batch-changes.md
Need to keep the old portal Batch Changes docs page temporarily to support links that are pointing to it.
> re-add Batch Change portal page to docs

- modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
- modules/portal/public/lib/controllers/controller.records.js
We use a configurable TTL value in DNS Changes in the portal but not in the Create Record Set modal in the Zones area of the portal.
- Use the configured TTL value in the Create Record Set modal. If a configuration isn't provided the fallback is 7200.
> use configured TTL in Create Record Set modal

- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/app/views/batchChanges/batchChangeNew.scala.html
- modules/portal/public/css/vinyldns.css
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
- modules/portal/public/lib/batch-change/batch-change.service.js
Trying this out. We may or may not decide to go with it.
- If manual review is enabled and the user submits a batch change with only soft errors we'll ask them to confirm they want to proceed to manual review. 
- change the alert message and change background colors to the warning yellow instead of danger red.
- Note: This first pass only includes the Zone Discovery Failed error message.
What else can we do in the portal to mitigate questions users might have about the review process?
> add review confirmation to DNS Change form

- modules/portal/app/controllers/FrontendController.scala
- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/app/views/batchChanges/batchChangeDetail.scala.html
- modules/portal/app/views/batchChanges/batchChanges.scala.html
- modules/portal/conf/routes
- modules/portal/public/lib/batch-change/batch-change-detail.controller.js
- modules/portal/public/lib/batch-change/batch-change.service.js
- modules/portal/public/lib/batch-change/batch-change.spec.js
- modules/portal/test/controllers/TestApplicationData.scala
- modules/portal/test/controllers/VinylDNSSpec.scala
- For super and support users give them the ability to approve or reject pending DNS Changes through the portal
> add DNS Change review ability to portal

- modules/docs/src/main/tut/api/list-batchchanges.md
Fixes #.
- noticed we didn't have the `approvalStatus` query parameter documented in the list batch changes API endpoint.
> add approvalStatus param to list batch changes doc [ci skip]

- modules/portal/app/views/batchChanges/batchChangeDetail.scala.html
- modules/portal/app/views/batchChanges/batchChanges.scala.html
- modules/portal/public/lib/batch-change/batch-changes.controller.js
A couple things that irked me in the DNS Changes area of the portal.
- Only show the Cancel button if a DNS Change has an approvalStatus of `PendingReview` **AND** the logged in account is the creator of the DNS Change. 
- In the "All Requests" tab add a column for Submitter and show the userName of who made the DNS Change.
- In the DNS Change details page show the submitter username if the logged in user didn't create the batch change.
> portal DNS Changes enhancements

- modules/api/functional_test/boto_request_signer.py
- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/vinyldns_python.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
Changes in this pull request in the BatchChangeService `buildResponse` method:
- if a manual review is enabled, a batch change has no errors, and is scheduled it goes to manual review. since there are no errors on the changes we don't need to verify if an owner group ID is present. (note: if manual review is disabled the batch change will fail earlier in the `applyBatchChangeValidationFlow`)
- if manual review is enabled system-wide and allowManualReview attribute on a batch is true it will go  to manual review if an owner group ID is specified, otherwise returns a ManualReviewRequiresOwnerGroup error.
> update send to manual review logic

- modules/api/functional_test/live_tests/membership/list_my_groups_test.py
- modules/api/functional_test/vinyldns_python.py
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/app/views/groups/groups.scala.html
- modules/portal/conf/routes
- modules/portal/public/lib/batch-change/batch-change-new.controller.js
- modules/portal/public/lib/batch-change/batch-change.spec.js
- modules/portal/public/lib/controllers/controller.groups.js
- modules/portal/public/lib/controllers/controller.groups.spec.js
- modules/portal/public/lib/controllers/controller.manageZones.js
- modules/portal/public/lib/controllers/controller.manageZones.spec.js
- modules/portal/public/lib/controllers/controller.records.js
- modules/portal/public/lib/controllers/controller.records.spec.js
- modules/portal/public/lib/controllers/controller.zones.js
- modules/portal/public/lib/controllers/controller.zones.spec.js
- modules/portal/public/lib/services/groups/service.groups.js
- modules/portal/public/lib/services/groups/service.groups.spec.js
- modules/portal/test/controllers/VinylDNSSpec.scala
- API: Add parameter `ignoreAccess` to list groups route. Default value is false.
- API: If `ignoreAccess` is true return groups regardless of requester's membership in the group
- Portal: add "My Groups" and "All Groups" tabs in the Groups page of the portal. Similar to the Zones tabs. View, Edit, and Delete buttons are visible based on group membership and admin rights.
Doesn't change existing behavior, though we may want to in future PRs:
- support and super users have access to all groups, regardless of the value of `ignoreAccess`
- non-admins cannot view individual groups they don't have access to, member lists or admin lists of those groups.
> Open list groups access

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/utils.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInputSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/notifier/email/EmailNotifierSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
- modules/core/src/main/protobuf/VinylDNSProto.proto
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/core/src/main/scala/vinyldns/core/domain/SingleChangeError.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/SingleChange.scala
- modules/core/src/main/scala/vinyldns/core/protobuf/BatchChangeProtobufConversions.scala
- modules/core/src/test/scala/vinyldns/core/protobuf/BatchChangeProtobufConversionsSpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
Prerequisite for remove single DNS record entry feature.
- Update protobuf for `SingleDeleteChange` to include an optional `recordData`
- Update unmarshalling to expect the correct data and output the correct types
Outstanding:
- Update unit and functional tests
> JSON deserialization and protobuf changes for remove single DNS record entry

- modules/api/functional_test/live_tests/membership/list_my_groups_test.py
- different test environments may have more or less groups so relax the "ignoreAccess" assertions to just ensure all groups are greater than my groups, and ignoreAccess is true.
> relax list group ignoreAccess assertions

- docker/api/docker.conf
- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
- modules/api/functional_test/live_tests/shared_zone_test_context.py
- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneServiceIntegrationSpec.scala
- modules/api/src/main/resources/application.conf
- modules/api/src/main/resources/reference.conf
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/access/AccessValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/access/AccessValidationsAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/access/GlobalAcl.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
- modules/api/src/test/scala/vinyldns/api/domain/access/AccessValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/access/GlobalAclSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- `GlobalACLs` - captures logic around testing a user's `AuthPrincipal` for access to a zone
- `AccessValidations` - modified the `getAccessLevel` to consult the `GlobalACLs` for a user to determine if the user has access.  `AccessValidations` now also takes `GlobalACLs`
- `VinylDNSConfig` - load the `GlobalACLs` from the config file
- `Boot` - load two separate `AccessValidations`.  One is used exclusively for batch changes that _will_ consult the configured global acls.  The other one used by the normal record set interface will not consult the global acls.  This is a TODO for cleanup
> Global ACLs

- modules/api/src/main/scala/vinyldns/api/repository/TestDataLoader.scala
- modules/portal/public/lib/services/groups/service.groups.js
- modules/portal/public/lib/services/groups/service.groups.spec.js
Following the same pattern we did for list groups, where we just set the default page size to 1000 when listing members.
- `service.groups.js` - modified the call to `getGroupMembers` to hard code the page size to 1000
- `service.groups.spec.js` - fixed unit tests
- `TestDataLoader` - added a sample group for dummy users that has all dummy users (200 of them) for simple testing.
> Set the maxItems to 1000 like list groups

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/core/src/main/scala/vinyldns/core/domain/SingleChangeError.scala
Support deleting a single DNS entry in batch change validations
- Add new error type for `DeleteRecord`
- Update batch change validation logic
- Add/update unit tests
> [DeleteRecord] Delete record validations

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/utils.py
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInputSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/mysql/src/main/resources/db/migration/V3.20__SingleChangeExpandSingleChangeType.sql
Remove multi-record config and support DeleteRecord inputs.
- Remove multi-record configs and associated errors
- Enable `DeleteRecord` input
- Update existing tests
Outstanding:
- Add more exhaustive (functional and unit) testing for `DeleteRecord`
Note: This PR is dependent on both https://github.com/vinyldns/vinyldns/pull/833 and https://github.com/vinyldns/vinyldns/pull/834.
> [DeleteRecord] Remove multi-record config

- modules/api/functional_test/live_tests/zones/get_zone_test.py
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
The terraform provider doesn't support batch change so users need to make records in shared zones through the recordset API endpoint. The recordset endpoint requires a zone ID, so terraform clients need to be able to get a zone by name to find out the zone id. 
This is a read-only endpoint so there's not a need for access validations based on zone ownership or system administration. There's also already initial validations at the routing endpoint to ensure locked users and users without access to the system cannot make the request.
- remove access validation from getZoneByName method in the Zone Service
> remove access validation from get zone by name service

- modules/core/src/main/scala/vinyldns/core/notifier/AllNotifiers.scala
Fixes #852 
- Adds logging to notification events by wrapping `notify.io` with a `monitor` class.
> Add logging around sent notifications in the API

- .travis.yml
- README.md
- bin/docker-up-vinyldns.sh
- docker/docker-compose-build.yml
- docker/docker-compose.yml
- docker/portal/application.conf
- modules/core/src/main/scala/vinyldns/core/notifier/AllNotifiers.scala
- modules/portal/app/controllers/LdapAuthenticator.scala
- modules/portal/app/controllers/Settings.scala
- modules/portal/test/controllers/LdapAuthenticatorSpec.scala
Support non ActiveDirectory LDAP
This PR has an optional local portal setup against this docker container - https://github.com/rroemhild/docker-test-openldap
The base modifications for LDAP was to change the actual authentication flow.  Before, we only attempted to bind (setting up a DirContext and relying on an exception).  We would test all of the search bases until we exhausted the list.
The new approach works differently:
1. First, login using the main service account
2. Second, do a lookup of the user
3. Finally, attempt to bind to that user's context directly using the password provided.
This works fine with both AD LDAP as well as the example docker container which uses OpenLDAP
Besides these changes, need to make configurable the userNameField, which is the ldap attribute that is …
> Support non ActiveDirectory LDAP

- modules/dynamodb/src/it/scala/vinyldns/dynamodb/repository/DynamoDBMembershipRepositoryIntegrationSpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlMembershipRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlMembershipRepository.scala
Fixes #868 
In `MySqlMembershipRepo` we unfortunately throw an exception if someone passes in an empty `Set` when trying to add or remove members in a group.  The effect should really be nothing instead of blowing up.
- `MySqlMembershipRepository` - added checks, if an empty set just return; otherwise process normally.  Added corresponding integration tests
- `DynamoDBMembershipRepository` - no changes, but just added some additional integration specs that work properly.
> Fix update group

- modules/mysql/src/main/resources/db/migration/V3.20__SingleChangeExpandSingleChangeType.sql
When multi-record support was initially reverted (https://github.com/vinyldns/vinyldns/pull/854), it included a SQL migration that was also migrated. Restoring that now.
> Restore SQL migration

- modules/portal/app/models/Meta.scala
- modules/portal/app/views/dnsChanges/dnsChangeNew.scala.html
- modules/portal/app/views/main.scala.html
- modules/portal/public/lib/dns-change/dns-change.directive.js
- modules/portal/test/models/MetaSpec.scala
portal flag for #867
- feature flag for the New DNS Change form that determines if the Record Data field shows for a change if the is a DeleteRecordSet type. 
- `multi-record-batch-change-enabled` config value defaults to false if not set. We use the term "DNS Change" in the portal but the config values for the API and portal should match hence the use of "batch-change".
- Include help text when the feature is enabled to let the user know when Record Data is not a required field.
Screenshot of portal with `multi-record-batch-change-enabled` set to true:
> feature flag portal multi-record batch change support

- docker/.env
- docker/docker-compose-build.yml
There is an issue with the current docker-up script that does not work with `latest` but does work with snapshot.  Changes here are necessary to get docker-up script working again.
> [ci skip] Temp fix for docker up until release

- docker/functest/run.sh
- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/utils.py
- modules/api/src/main/resources/application.conf
- modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInputSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/notifier/email/EmailNotifierSpec.scala
- modules/api/src/test/scala/vinyldns/api/notifier/sns/SnsNotifierSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeRoutingSpec.scala
- modules/core/src/main/protobuf/VinylDNSProto.proto
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/SingleChange.scala
- modules/core/src/main/scala/vinyldns/core/protobuf/BatchChangeProtobufConversions.scala
- modules/core/src/test/scala/vinyldns/core/protobuf/BatchChangeProtobufConversionsSpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
Prototype for multi-record enabled.
Changes in this PR:
- Allow optional `record` data with `DeleteRecordSet` requests (controlled by configuration value of `multi-record-batch-change-enabled`)
Outstanding issues:
- Update functional tests (with testing behavior dependent on multi-record enabled)
> Enable multi-record functionality in batch change

- README.md
-Added license-badge to Readme
Screen Shot from Atom Markdown Preview:
> add license badge to Readme

- bin/func-test-api-travis.sh
- bin/func-test-api.sh
- docker/docker-compose-func-test.yml
- docker/functest/Dockerfile
- docker/functest/run.sh
Allow overriding of the number of CPUs to use for running func tests.  Leaving this as an override as `auto` is not always optimal and will depend on the machine performing the func tests.
> Allow overriding parallelism for func tests

- docker/.env.build
- docker/docker-compose-build.yml
Right now, the `.env` configuration file is shared between
multiple `docker-compose` configurations. However, these
configurations actually need different environments; for example,
`docker-compose-build.yml` runs a local DynamoDB via `localstack`,
whereas `docker-compose-func-test.yml` runs it via `dynamodb-local`.
(Incidentally, this leads to the [quickstart](https://github.com/vinyldns/vinyldns/blob/master/README.md#quickstart) not working properly, as
documented in #887).
This changes creates a separate `.env.build` file for use by the
`docker-compose-build.yml` and updates it to point to the correct
location of the local DynamoDB.
Fixes #887.
- create new environment variable file for running locally
> Use a separate environment configuration for running locally.

- modules/api/src/main/scala/vinyldns/api/route/BatchChangeJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/route/BatchChangeJsonProtocolSpec.scala
- add record data to the DeleteRRSetChangeInputSerializer `toJson` method so record data is returned in responses if it was included in requests.
> update DeleteRRSetChangeInputSerializer toJson method

- DEVELOPER_GUIDE.md
- update the instructions for running VinylDNS locally so `dockerComposeUp` and `dockerComposeStop` are run from the root project rather than one of the submodule projects.
> update Developer Guide

- docker/api/logback.xml
- docker/docker-compose-quick-start.yml
- modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
Seems like we had a PR that took away access logs.
- `VinylDNSService.scala` - make sure to use the correct routes with logging, before we were not using the logged routes
- `logback.xml` - added this as an example so others can follow on more overrides for logging
> Fix - Adding access logging

- modules/portal/app/views/dnsChanges/dnsChangeDetail.scala.html
- modules/portal/app/views/dnsChanges/dnsChangeNew.scala.html
- modules/portal/app/views/dnsChanges/dnsChanges.scala.html
- modules/portal/app/views/main.scala.html
- modules/portal/public/app.js
- modules/portal/public/lib/dns-change/dns-change-detail.controller.js
- modules/portal/public/lib/dns-change/dns-change-new.controller.js
- modules/portal/public/lib/dns-change/dns-change.directive.js
- modules/portal/public/lib/dns-change/dns-change.module.js
- modules/portal/public/lib/dns-change/dns-change.service.js
- modules/portal/public/lib/dns-change/dns-change.spec.js
- modules/portal/public/lib/dns-change/dns-changes.controller.js
Fixes https://github.com/vinyldns/vinyldns/issues/873
- Renames module, controllers, service and directive in modules/portal/public/lib/dns-change/ from BatchChange to DnsChange
- Updates their uses and references.
> Rename batchChange module/controller/service to dnsChange

- docker/docker-compose-func-test.yml
- docker/functest/run.sh
Currently we use a BIND9 image which mounts the zone files on spin up, but we can use the `vinyldns/test-bind9` image which to circumvent issues with mounting.
Also corrected an issue where the docker func scripts were only running parallel tests.
> Use test bind9 image

- modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
- modules/api/src/main/scala/vinyldns/api/engine/BatchChangeHandler.scala
- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
- modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/BatchChangeHandlerSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/RecordSetChangeHandlerSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/BatchChange.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/ZoneCommand.scala
- modules/mysql/src/it/scala/vinyldns/mysql/queue/MySqlMessageQueueIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/queue/MessageType.scala
- modules/mysql/src/main/scala/vinyldns/mysql/queue/MySqlMessageQueue.scala
- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessage.scala
- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala
- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageType.scala
- modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageQueueSpec.scala
- modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageSpec.scala
- modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageTypeSpec.scala
Currently the notifications for batch changes are fired during the record set change processing stage, but there is an edge case where the notification doesn't trigger despite processing completion. Queueing a new batch change command allows us the following:
- Retries on the processing notification
- Middle ground before batch processing is supported by the `CommandHandler`.
> Convert batch change notification to command

- modules/portal/app/controllers/FrontendController.scala
- modules/portal/app/models/DnsChangeNotices.scala
- modules/portal/app/views/dnsChanges/dnsChangeDetail.scala.html
- modules/portal/app/views/main.scala.html
- modules/portal/conf/reference.conf
- modules/portal/public/css/theme-overrides.css
- modules/portal/public/lib/directives/directives.notices.js
- modules/portal/public/lib/dns-change/dns-change-detail.controller.js
- modules/portal/public/templates/notice.html
- modules/portal/test/models/DnsChangeNoticesSpec.scala
- project/Dependencies.scala
- Add configurable notices to the DNS Change detail page based on the DNS Change status. The notices are intended to give users additional context about the state of their DNS Change.
- Config key is "dnsChangeNotices" and requires a list. The list can be empty or contain objects with the attributes: "status", "text", "alertType", "href" (optional), "hrefText" (optional).
- status is matched against our current list of valid batch change statuses: Cancelled, Complete, Failed, PartialFailure, PendingProcessing, PendingReview, Rejected, Scheduled. If the given status doesn't match we set the status to "Unknown". This determines which notice appears on which DNS Change.
- alertType is matched against a list of valid Bootstrap 3 alert types: info, success, …
> DNS Change detail notices

- modules/portal/app/views/dnsChanges/dnsChangeNew.scala.html
- modules/portal/public/lib/dns-change/dns-change.directive.js
- modules/portal/public/lib/dns-change/dns-change.spec.js
- add an invalid IP check to the CNAME record data field in the DNS Change form. If the record data is an IPV4 address (with or without a trailing dot) return an error that states "CNAME data must be a domain name, not an IP address!" Opted for this new message as opposed to tying it into the existing FQDN validation in order to provide users with more context about why the data they provided is invalid, and help them understand that CNAMES are for FQDNS not IP addresses. 
Intentionally kept the scope of this PR small, but we should make additional changes to the FQDN regex in the portal and the API to not allow IP addresses to be considered valid FQDNs. It's a little tricky right now between the regex and the way we handle adding trailing dots. I believe we …
> validate CNAME record data is not an IP address in DNS Change form

- modules/docs/src/main/tut/api/batchchange-model.md
- Change batch change limit of 20 to note that the batch change limit is dependent on the instance. We already state that throughout the docs but it was missed here.
> update batch change limit info in the docs

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/vinyldns_python.py
- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
- modules/api/src/test/scala/vinyldns/api/engine/RecordSetChangeHandlerSpec.scala
close #842 
Retry failed record changes if the record change error is Refused during the apply step of the finite state machine, or if the record change error is Try Again during the verify step of the finiite state machine in the RecordSetChangeHandler. Raising an error in the RecordSetChangeHandler causes the change to go back on the MySqlMessageQueue.
Tested against a commonly failing scenario, changing an A record to a CNAME through a batch change. Currently the A record deletes successfully but the CNAME fails in the backend. With the re-queue the CNAME add appears to succeed.
record statuses based on current flow:
record statuses based on updated flow:
Need to add/update more tests.
> retry some failed record changes

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/functional_test/vinyldns_python.py
- Remove transiently passing functional test due to sufficient coverage via unit tests
- Revert `MAX_RETRIES` value
> Remove functional test and revert MAX_RETRIES

- modules/api/functional_test/live_tests/batch/create_batch_change_test.py
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
For Batch Changes we now accept record data for DeleteRecordSet to delete only specific records in a recordset rather than the entire recordset. We do an exact match on the existing records in the recordset which is fine for most record data types, except IPv6 address for AAAA records. They can be written in many forms and we should match our existing records across any given format.
- try to match the given IPv6 address with existing record data in `BatchChangeValidations`
- choose the existing record data that is the equivalent of the given record data in `BatchTransformations`
> make Batch Change AAAA record data flexible

- modules/api/src/main/resources/reference.conf
- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
- modules/api/src/main/scala/vinyldns/api/route/VinylDNSDirectives.scala
- modules/core/src/main/scala/vinyldns/core/queue/MessageQueueConfig.scala
- modules/core/src/test/scala/vinyldns/core/queue/MessageQueueLoaderSpec.scala
- modules/docs/src/main/tut/operator/config-api.md
- modules/mysql/src/it/resources/application.conf
- modules/mysql/src/main/scala/vinyldns/mysql/queue/MySqlMessageQueue.scala
- modules/mysql/src/main/scala/vinyldns/mysql/queue/MySqlMessageQueueProvider.scala
- modules/mysql/src/test/scala/vinyldns/mysql/queue/MySqlMessageQueueProviderSpec.scala
- modules/mysql/src/test/scala/vinyldns/mysql/repository/MySqlDataStoreProviderSpec.scala
- modules/portal/app/models/DnsChangeNotices.scala
- modules/sqs/src/it/resources/application.conf
- modules/sqs/src/it/scala/vinyldns/sqs/queue/SqsMessageQueueProviderIntegrationSpec.scala
Changes in this PR:
- Add new optional `maxRetries` config value for `MySqlMessageQueue` with default value of 100
- Update example config in documentation
----
Note: If encountering a config error during API boot, try doing a clean (`sbt ";project api ;clean ;run"`).
> Add max retries to MySQL queue configuration

- modules/api/functional_test/live_tests/membership/list_group_members_test.py
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/MembershipJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/route/CreateGroupInputSerializerSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/UpdateGroupInputSerializerSpec.scala
Noticed our get group endpoint was returning all user lock statuses with the value of Unlocked even if the user is Locked. Looked into this more closely and realized we're using the UserInfo class as part of the response. In the UserInfo class all fields are optional except ID and LockStatus, but when retrieving a group we only have the member IDs so I set a default LockStatus of Unlocked on initial implementation. 
In reality if we're only handling user IDs in certain instances we should just be using a type that only includes the user ID as an attribute. I added UserID that is used in the get, create and update group endpoints. And updated UserInfo to not have a default LockStatus. This also removes LockStatus from the get group endpoint which matches what our documentation currently …
> fix user lock status in group response

- modules/portal/app/views/dnsChanges/dnsChangeNew.scala.html
There's confusion over which domains go in which DNS Change form fields for CNAME records. Both of the placeholder values are currently "test.example.com". We can change the placeholder values to be more helpful.
- change the Input Name placeholder to "alias.example.com"
- change the Record Data placeholder to "answer.example.com"
> update CNAME placeholders in DNS Change form

- modules/portal/app/views/groups/groups.scala.html
- modules/portal/app/views/zones/zones.scala.html
We have view buttons in the Groups and Zones list pages that link to groups and zones users have access too, but we could also help by linking the names in the tables to the detail pages.
- If a user has access to view a zone or group link the name to the detail page.
> link group and zone names to detail pages

- bin/func-test-api-testbind9.sh
- docker/docker-compose-func-test-testbind9.yml
- Revert `bin/func-test-api.sh` to use `vinyldns/bind9` image for default func tests (to pull local BIND9 files)
- Clone a copy of func test and docker to use `vinyldns/testbind9`
> Use vinyldns/bind9 image for func test

- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetChangeGenerator.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneView.scala
- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneViewSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/RecordSetChangeHandlerSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/record/RecordSetChange.scala
Tied to https://github.com/vinyldns/vinyldns/issues/853.
- Introduce new `RecordSetChangeType.Sync` and `RecordSetChangeStatus.Synced` enumerations
- Implement a sync against DNS backend check that happens during the `validate` stage of record set change processing
> Implement record set sync against DNS backend in RecordSetChangeHandler process flow

- modules/api/functional_test/live_tests/recordsets/update_recordset_test.py
- modules/api/functional_test/live_tests/zones/sync_zone_test.py
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
We want to prevent users from changing recordset names and types during recordset updates. If a user is trying to change a recordset name or type they should really be creating a new record and deleting the existing record. This is going to help us move toward being able to display recordset change history based on the unique combination of a recordset's name and type.
- Add RecordSet validation to confirm the recordset name, type and zone ID in the given data for recordset update matches the name of the existing recordset. we already checked for zone ID changes, but this moves that into the same validation.
> disallow recordset name and type updates

- modules/portal/conf/reference.conf
Awhile back we increased the default value of maximum record changes in a batch change to 1000. However we did not account for the Play framework's maximum content length of 100kb. I tested the largest batch changes we might see and and came away with 375kb as a threshold that they be under. We might have reason to increase this further in the future if our supported record types in the DNS Change form in the portal changes.
Source for the content length information: https://www.playframework.com/documentation/2.5.x/ScalaBodyParsers#Max-content-length
> increase Play Framework maxMemoryBuffer to support large DNS Change requests

- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetChangeGenerator.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
There is a chance that the database is out-of-sync with the DNS backend. Rather than require for a change to be dependent on a zone sync if the DNS change would be permitted otherwise, we can allow the validation to be accepted and process it normally in the DNS backend.
- Allow certain scenarios to pass record set validations
> Allow exceptions to record set validations depending on disposition of DNS backend

- modules/portal/app/views/recordsets/recordSets.scala.html
- modules/portal/public/lib/controllers/controller.records.js
- modules/portal/public/lib/controllers/controller.records.spec.js
- modules/portal/public/lib/recordset/recordsets.controller.js
- Add information about global record search criteria
- Don't invoke page refresh when toggling record types
> Don't refresh when toggling record types during record set search

- project/Dependencies.scala
Upgrade one more dependency, `scalikejdbc` to `3.4.1`. Needed to do this for some weird edge-case stuff when using the vinyl artifacts in other tools/clients -- we were getting some issues with the version of `scala-collection-compat` that `scallikejdbc` `3.3.1` included. It does not appear that there are any issues in rolling this forward.
> Upgrade scalikejdbc version

- modules/api/functional_test/live_tests/recordsets/create_recordset_test.py
The BLOB type is juuuust too small for the previous value. Reduce the
number of characters by two -- the purpose of the test is still being
fulfilled. A migration to MEDIUMBLOB or LARGEBLOB will be required if we
need this to be bigger.
> Slightly reduce long txt record test size

- modules/api/src/it/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
- modules/api/src/test/scala/vinyldns/api/engine/TestMessageQueue.scala
- modules/core/src/main/scala/vinyldns/core/health/HealthCheck.scala
- modules/core/src/test/scala/vinyldns/core/health/HealthServiceSpec.scala
- modules/dynamodb/src/main/scala/vinyldns/dynamodb/repository/DynamoDBDataStoreProvider.scala
- modules/mysql/src/main/scala/vinyldns/mysql/queue/MySqlMessageQueue.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlDataStoreProvider.scala
- modules/portal/app/controllers/LdapAuthenticator.scala
- modules/portal/test/controllers/HealthControllerSpec.scala
- modules/portal/test/controllers/LdapAuthenticatorSpec.scala
- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala
Previously if a health check failed, there was no way of knowing _which_
one failed, unless you can isolate the particular type of failure --
though they're often very general (connection timeout, etc). If a health
check fails, it's important to know which one, or at least to log which
one it was.
I'm not sure if there's a way to infer the calling class without doing
some gnarly and expensive call-stack stuff, so here's a simple fix. If
there's a better way, I'm all ears.
I did experiment a little bit parameterizing the HealthCheck, but that
honestly seemed like more trouble than it was worth for now.
Fixes #.
- .asHealthCheck takes a single parameter, a class type, enabling more 
descriptive logging
> .asHealthCheck takes a class param for reporting

- bin/update-support-user.sh
- docker/admin/Dockerfile
- docker/admin/update-support-user.py
In order to update support users, we need to be able to unpack/pack the VinylDNS protobuf.
This requires us to 1) compile the proto file and 2) call out to the vinyldns Database
Added `update-support-user.py` that provides a simple way to pass in a vinyldns username and `Boolean` to update a user to be a support user.
Built a dockerfile that compiles the Vinyldns.proto file to Python.  This is to avoid a user from having to have `protoc` installed locally and having to know the correct commands.  An alternative would be to run `protoc` and output the proto file to `target` or something.  This approach requires `docker` which felt preferable, but I could go either way.
To execute, you must setup the environment variables or pass them in on the command line.
```
> …
```
> Adding scripts to update support users

- modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
- modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
- modules/portal/public/lib/services/groups/service.groups.js
Groups ultimately need pagination and searching (#603, #415) as well as support for LDAP (#929) groups. As such this fix is to extend the life of the existing implementation until we have time to revisit this (likely with #968).
> Increase max groups list result size

- bin/docker-up-vinyldns.sh
- docker/.env
- docker/.env.quickstart
Changed up the docker quick start to assert the latest tagged release unless overridden via the version argument
> [ci skip] Change docker quickstart

- modules/portal/app/views/dnsChanges/dnsChangeDetail.scala.html
Fixes #995.
- `dnsChangeDetail.scala.html` modified with the introduction of a `textArea` instead of the `input` tag.
> review comment replaced with text area

- modules/api/src/it/scala/vinyldns/api/route53/Route53ApiIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/Fqdn.scala
- modules/r53/src/it/scala/vinyldns/route53/backend/Route53IntegrationSpec.scala
- modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala
- modules/r53/src/main/scala/vinyldns/route53/backend/Route53Conversions.scala
Fixes #1012 
- When available, ensure that the `zoneId` is passed when loading vinyldns record sets
- Use the `DelegationSet` on the hosted zone to _simulate_ NS records.  NS records do not exist by default on private hosted zones
> Route 53 fixes for connect

- modules/core/src/main/scala/vinyldns/core/domain/Fqdn.scala
- modules/core/src/test/scala/vinyldns/core/domain/FqdnSpec.scala
Addresses #1012
Was able to get a "real" public hosted zone connected.  The `Fqdn.merge` was not working properly when merging record name and zone names when they matched.
Added a bunch of unit tests along with the fix.
This was tested against a "real" public hosted zone.  Verified connect, load zone, add record, delete record.
> Fix route53 issue with merge fqdn

- modules/portal/app/controllers/OidcAuthenticator.scala
- modules/portal/test/controllers/OidcAuthenticatorSpec.scala
Tenant id is not uniformly used across all OIDC providers (such as keycloak).
Make tenant id in configuration and the corresponding OIDC flow check optional for the time being.  
Need to overhaul the OIDC portal code which is well underway but not ready yet, so this is a temporary workaround.
> Make tenant id optional

- modules/api/src/main/resources/application.conf
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
- modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
- modules/portal/prepare-portal.sh
Fixes #1034 
- Update record view for managing records to _not_ display a warning next to records that are valid dotted hosts.
- Update the prepare portal script to do a force (needed for clean machine)
- Add queue coordinates for starting up the api locally using `reStart` - the coordinates were removed from `reference.conf` in a prior PR that looks to have broken starting up using `reStart` locally
- Added a unit test to double check we allow dotted TXT records in the API
> Drop warning for dotted hosts on valid records

- modules/api/src/test/scala/vinyldns/api/backend/CommandHandlerSpec.scala
- modules/portal/app/actions/ApiAction.scala
- modules/portal/app/actions/FrontendAction.scala
- modules/portal/app/actions/LegacySecuritySupport.scala
- modules/portal/app/actions/VinylDnsAction.scala
- modules/portal/app/controllers/OidcAuthenticator.scala
- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/app/views/setOidcSession.scala.html
- modules/portal/test/controllers/FrontendControllerSpec.scala
- modules/portal/test/controllers/OidcAuthenticatorSpec.scala
- modules/portal/test/controllers/VinylDNSSpec.scala
- version.sbt
With the release of `0.10.0` the redirect for OIDC authentication was not working.
- Re-enable redirect in `setOidcSession.scala.html`
- Add support for redirecting to requested page after login, rather than `/index`-purgatory
> Fix portal login redirect

- modules/portal/public/lib/dns-change/dns-change-new.controller.js
Fixes portal bug where CSV lines with commas in quoted fields were truncated/split at the commas not the surrounding quotes.
- Parse CSV lines containing quoted commas properly
> Parse CSV lines containing quoted commas properly

- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordSetRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
- Resolve SQL injection vulnerability in Recordset Search. Replaced normal strings with `sqls` which prevents SQL injection.
- Used `sqls""` from Scalikejdbc library which gives protection against SQL Injection. `sqls""` always treats external input values as binding parameters. For more info: [Scalikejdbc SQLInterpolation](http://scalikejdbc.org/documentation/sql-interpolation.html)
- Tested the changes locally and it’s working as expected.
> Resolve SQL injection vulnerability

- modules/api/src/test/functional/tests/recordsets/update_recordset_test.py
- modules/api/src/test/scala/vinyldns/api/domain/access/AccessValidationsSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/ACLRule.scala
- modules/docs/src/main/mdoc/permissions.md
Currently, if multiple ACL entries are associated with a user, the LEAST permissive is returned. For example, if a user has an entry with Write permission, and another with Read, that user will only be able to read.
This functionality has been changed to now return the MOST permissive rule. In the previous example, the user would be able to both read and write, because Write takes precedence by nature of being more permissive.
The NoAccess permission is treated as the highest priority, and takes precedence over other rules.
Fixes #1083
> ACLs Should Honor Most Permissive Access Level

- .github/workflows/notify.yml
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
- modules/api/src/test/functional/tests/membership/get_group_changes_test.py
- modules/api/src/test/functional/tests/membership/get_group_test.py
- modules/api/src/test/functional/tests/membership/list_group_admins_test.py
- modules/api/src/test/functional/tests/membership/list_group_members_test.py
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipValidationsSpec.scala
- modules/portal/app/views/groups/groups.scala.html
All logged in users can now view the group details of any group, not just groups they are part of. This allows users to see the members and admins of other groups without reaching out to support. This is read-only, users still cannot modify groups they are not part of.
Resolves https://github.com/vinyldns/vinyldns/issues/1088
> Allow Users to View Members of Other Groups

- modules/api/src/main/resources/reference.conf
- modules/portal/conf/reference.conf
Hotfix for changes made in https://github.com/vinyldns/vinyldns/pull/1104
The new config variable `flyway-out-of-order` was only added to application.conf in the previous PR. It also needs to be added to reference.conf in order to start the portal correctly.
> Hotfix: Flyway Migration Issue

- modules/api/src/it/resources/application.conf
- modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala
Fixes #1042
Because `Algorithm` is a sealed case class, PureConfig will by default expect a object in the config file. It needs a custom `ConfigReader` to instead ingest only a simple string, and turn it into the appropriate instance. The custom reader is placed inside the companion object so it is always automatically in scope. I opted for a [cursor-based one](https://pureconfig.github.io/docs/error-handling.html#validations-in-custom-readers) so I can re-use the `fromString` method as-is and nicely integrate it with PureConfig's validation capabilities. 
Adding the `algorithm` key with the default value to the `application.conf` for integration test of the `api` module was enough to reproduce/trigger the error, and serves as test for the bugfix.
> Fix loading TSIG algorithm from config

- modules/portal/public/lib/services/records/service.records.js
- Added http status code check for the recordset search spinner. This will hide the spinner, when user, search records with null(empty) in Global recordset.
> Added http status code check for the recordset search spinner

- build/docker/api/application.conf
- build/docker/api/logback.xml
- modules/api/src/it/resources/application.conf
- modules/api/src/main/resources/application.conf
- modules/api/src/main/resources/logback.xml
- modules/api/src/main/resources/test/logback.xml
- modules/api/src/main/scala/vinyldns/api/route/Aws4Authenticator.scala
- modules/api/src/test/resources/application.conf
- modules/api/src/universal/conf/application.conf
- modules/core/src/test/resources/logback.xml
- modules/docs/src/main/mdoc/operator/config-api.md
- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala
- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueueProvider.scala
- quickstart/docker-compose.yml
- test/api/functional/application.conf
- test/api/integration/application.conf
The goal of this PR to improve the logging in various ways. Below is a listing of the full commit messages with detailed explanations.
[Appenders in logback are additive](https://logback.qos.ch/manual/configuration.html#cumulative), specifying them multiple times leads to log lines being output multiple times. It is usually enough to set the appender on the root logger, and nowhere else.
Setting the same log level on multiple package levels is also kind of unneeded, the top-most one would be enough.
Let's establish a sane default by not having flyway run on full-blast debug output by default. For normal operation I found INFO to be verbose enough (as the flyway devs intended I guess).
Fixes #864
As the existing code comment said, it is for debugging; so make it DEBUG level. This means ~15 …
> Various logging fixes

- build/docker/api/logback.xml
- build/docker/portal/logback.xml
- quickstart/quickstart-vinyldns.sh
- Allow log level to be set via environment
- Remove `envsubst` from `quickstart.sh` for macOS compat
> Minor Updates

- modules/portal/public/lib/controllers/controller.groups.js
- modules/portal/public/lib/recordset/recordsets.controller.js
Fixes #1183.
- Fix for autocomplete recordset and group search feature, where safari browser not set the value selected in auto complete dropdown.
> Fix for safari issue in autocomplete search

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/test/functional/tests/batch/create_batch_change_test.py
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/SingleChange.scala
Fixes #1138 
- If a user requests the deletion of records that does not exist, we now allow the change with a message `This record does not exist. No further action is required.` next to the affected records without throwing an error.
> Allow deletion of records that doesn't exist

- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
- modules/api/src/main/scala/vinyldns/api/route/MembershipJsonProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
- modules/api/src/test/functional/tests/membership/get_group_changes_test.py
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/membership/GroupChange.scala
- modules/core/src/main/scala/vinyldns/core/domain/membership/GroupChangeRepository.scala
- modules/core/src/test/scala/vinyldns/core/TestMembershipData.scala
- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/app/views/groups/groupDetail.scala.html
- modules/portal/conf/routes
- modules/portal/public/lib/controllers/controller.membership.js
- modules/portal/public/lib/controllers/controller.membership.spec.js
- modules/portal/public/lib/services/groups/service.groups.js
- modules/portal/test/controllers/TestApplicationData.scala
- modules/portal/test/controllers/VinylDNSSpec.scala
Fixes #1153 
- Added `group change history` in portal to view what changes have been made to groups (admin added & removed, member added & removed etc) and by whom it was made. It was done similar to `record set changes history` in zones view.
> Add group change history

- DEVELOPER_GUIDE.md
- Updated the developer guide to add Support for M1 Macs section, which details the dependencies whose versions should be updated before attempting to run VinylDNS locally on a Mac running on Apple silicon
> Update documentation for Apple M1 support

- modules/api/src/main/resources/reference.conf
- modules/portal/public/lib/services/groups/service.groups.js
Fixes #1142.
- Revert the `groups maxItems` that was changed in the [groups pagination PR](https://github.com/vinyldns/vinyldns/pull/1142) to how it was before, so that we don't see only 100 groups in dropdown.
> Revert groups maxItems (PR #1142 fix)

- modules/api/src/it/resources/application.conf
- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/main/resources/application.conf
- modules/api/src/main/resources/reference.conf
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/config/DottedHostsConfig.scala
- modules/api/src/main/scala/vinyldns/api/config/VinylDNSConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeService.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/test/functional/tests/recordsets/create_recordset_test.py
- modules/api/src/test/functional/tests/shared_zone_test_context.py
- modules/api/src/test/scala/vinyldns/api/VinylDNSTestHelpers.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/repository/EmptyRepositories.scala
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/core/src/main/scala/vinyldns/core/domain/SingleChangeError.scala
- modules/core/src/main/scala/vinyldns/core/domain/membership/GroupRepository.scala
- modules/core/src/test/scala/vinyldns/core/TestMembershipData.scala
- modules/core/src/test/scala/vinyldns/core/TestZoneData.scala
- modules/docs/src/main/mdoc/operator/config-api.md
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlGroupRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
- modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
- Added a config with settings which are used to allow the creation of dotted hosts.
- Details about the config can be found in `modules/docs/src/main/mdoc/operator/config-api.md`.
> Allow dotted hosts creation using config

- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
Fixes #1187 
- When we `update` a created dotted host, we currently get an error and doesn’t allow us to `update`. The problem is with the validation which is added to check the conflict while `creating` dotted hosts. That validation is not necessary to be in `update` since we already handle it while `creating` and recordset name cannot be changed during `update`. 
- Removed the validation from `update` now and it works as expected.
- Added tests to verify the working.
> Fix dotted hosts update (PR #1187)

- modules/api/src/main/resources/reference.conf
- modules/portal/public/lib/services/groups/service.groups.js
Fixes #1196
Currently we are hitting the 1500 item limit for groups that can be displayed in a dropdown. This fix increases the limit to 3000.
> Hotfix: Raise Limit of Maximum Items in a Group List to 3000

- modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/ZoneChange.scala
- modules/core/src/test/scala/vinyldns/core/TestZoneData.scala
- modules/core/src/test/scala/vinyldns/core/domain/zone/ZoneChangeSpec.scala
- modules/core/src/test/scala/vinyldns/core/protobuf/ProtobufConversionsSpec.scala
Fixes #618 
- Remove the zone change status `Complete` and it's occurrences since it is not being used anywhere other than tests.
> Remove 'Complete' zone change status

- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala
Fixes #408 
- Excluded zone connection key and algorithm to prevent accidental logging of sensitive info by overriding `toString` in ZoneConnection. Validated that it doesn't show up in any log statements and also that Zone `toString` has the zone connection in this format.
> Override ZoneConnection toString

- modules/api/src/main/scala/vinyldns/api/backend/dns/DnsConversions.scala
- modules/api/src/test/functional/tests/recordsets/create_recordset_test.py
- modules/api/src/test/scala/vinyldns/api/backend/dns/DnsConversionsSpec.scala
Fixes #570 
- Made changes similar to the PR: #568 which fixes a similar issue for TXT records. Group SPF record data as a list of 255 character length strings.
> Correctly handle SPF record data 

- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipValidationsSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/membership/User.scala
- modules/portal/test/controllers/TestApplicationData.scala
Fixes #444 
- Excluded access and secret keys to prevent accidental logging of sensitive info by overriding `toString` in User, and validated that it doesn't show up in any log statements.
> Remove keys from User by overriding 'toString'

- modules/api/src/main/scala/vinyldns/api/route/StatusRouting.scala
- modules/api/src/main/scala/vinyldns/api/route/VinylDNSService.scala
- modules/api/src/test/functional/tests/internal/status_test.py
- modules/api/src/test/functional/tests/shared_zone_test_context.py
- modules/api/src/test/scala/vinyldns/api/VinylDNSTestHelpers.scala
- modules/api/src/test/scala/vinyldns/api/route/StatusRoutingSpec.scala
Fixes #366 
- Added auth on POST /status. Now, only the admin users can do a POST request on /status using their access key and secret key for authentication.
> Add auth on POST /status

- modules/api/src/main/scala/vinyldns/api/domain/access/AccessValidations.scala
- modules/api/src/test/functional/tests/zones/get_zone_test.py
- modules/api/src/test/functional/tests/zones/list_zones_test.py
- modules/api/src/test/scala/vinyldns/api/domain/access/AccessValidationsSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
- modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
- modules/portal/public/lib/controllers/controller.records.js
- modules/portal/public/templates/record-modal.html
Fixes #643
All users are able to make changes within shared zones, so it makes sense that they should be able to view the shared zones as well. This change allows all users to view a shared zone regardless of membership
> Allow All Users to View Any Shared Zone

- build.sbt
- modules/api/src/main/scala/vinyldns/api/config/HighValueDomainConfig.scala
- modules/api/src/main/scala/vinyldns/api/config/ManualReviewConfig.scala
- modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/AclRuleOrdering.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneRecordValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneValidations.scala
- modules/api/src/test/functional/tests/batch/create_batch_change_test.py
- modules/api/src/test/functional/tests/recordsets/create_recordset_test.py
- modules/api/src/test/functional/tests/zones/update_zone_test.py
- modules/api/src/test/scala/vinyldns/api/VinylDNSTestHelpers.scala
- modules/api/src/test/scala/vinyldns/api/domain/ReverseZoneHelpersSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/access/AccessValidationsSpec.scala
- project/Dependencies.scala
Fixes #235.
- Replaced `orchard CIDR` library to `com.comcast IP4s` library.
- Upgraded `IP4s` version from `1.1.1` to `3.1.3`(latest)
> Replaced orchard CIDR library to IP4s library

- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/test/scala/vinyldns/api/CatsHelpers.scala
- modules/api/src/test/scala/vinyldns/api/ResultHelpers.scala
- modules/api/src/test/scala/vinyldns/api/domain/auth/MembershipAuthPrincipalProviderSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeInterfacesSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneConnectionValidatorSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/BatchChangeHandlerSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/RecordSetChangeHandlerSpec.scala
Fixes #464 
- Replaced `await` and other related functions present in `CatsHelpers.scala` and `ResultHelpers.scala` which is not necessary with cats `IO` library as we switched over.
> Replace await with IO

- modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
- modules/api/src/main/scala/vinyldns/api/backend/dns/DnsBackend.scala
- modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
- modules/api/src/main/scala/vinyldns/api/notifier/sns/SnsNotifier.scala
- modules/core/src/main/scala/vinyldns/core/health/HealthCheck.scala
- modules/core/src/main/scala/vinyldns/core/notifier/AllNotifiers.scala
- modules/core/src/main/scala/vinyldns/core/route/Monitor.scala
- modules/core/src/main/scala/vinyldns/core/task/TaskScheduler.scala
- modules/core/src/test/scala/vinyldns/core/route/MonitorSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/TransactionProvider.scala
- modules/mysql/src/main/scala/vinyldns/mysql/queue/MySqlMessageQueue.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlDataStoreProvider.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetCacheRepository.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
- modules/portal/app/controllers/LdapAuthenticator.scala
- modules/portal/app/controllers/OidcAuthenticator.scala
- modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala
Fixes #1209.
- Trims the log messages that have multi line messages to single line. Replaced the `\n` and `\t` characters with `;` and ` ` characters in the log message to make it single line.
> Trim multi line log messages to single line

- modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
Fixes #1211.
- Added an override method to convert the json response fields `created` and `latestSync` to `string` type instead of `int`.
> Resolve datetime json response

- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
Fixes #1201.
- Updated group change history message to display `username` instead of `userid` when there's a change in members or admins of the group,  to make it easier to find out who is added or removed.
> Update group history message

- modules/api/src/main/scala/vinyldns/api/domain/record/ListRecordSetChangesResponse.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/test/functional/tests/recordsets/list_recordset_changes_test.py
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/record/ListRecordSetChangesResults.scala
- modules/core/src/main/scala/vinyldns/core/domain/record/RecordChangeRepository.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordChangeRepository.scala
Fixes #566
- Updated record change paging in api to paginate properly using `LIMIT` and `OFFSET`, like while listing and paginating in [batch changes](https://github.com/vinyldns/vinyldns/blob/5e9616c12f61d59708c2fff0dc5ad3ff4903467d/modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala#L234)
> Update zone record change pagination

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
- modules/api/src/test/functional/tests/batch/create_batch_change_test.py
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/core/src/main/scala/vinyldns/core/domain/SingleChangeError.scala
- modules/core/src/main/scala/vinyldns/core/domain/batch/SingleChange.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlBatchChangeRepositoryIntegrationSpec.scala
- modules/portal/app/views/dnsChanges/dnsChangeDetail.scala.html
Fixes #1217.
- When user submit add and delete for non-existent record with same record data in the batch, it displays a validation error.
- When user submit add and delete for non-existent record with different record data in the batch, it just creates the record and omits the delete request as changes made for the issue [Requested record deletes with (RecordDoesNotExist) should not prevent batch submission #1138](https://github.com/vinyldns/vinyldns/issues/1138)
> Fix batch change validation bug

- modules/api/src/main/scala/vinyldns/api/domain/record/ListRecordSetChangesResponse.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ListZoneChangesResponse.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/record/RecordChangeRepository.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/ZoneChangeRepository.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordChangeRepository.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
Fixes #439.
> Added metrics api for zone change failure and record change failure.
```
/metrics/health/zonechangesfailure
/metrics/health/recordsetchangesfailure
```
> Added metrics api for zone change failure and record change failure

- modules/api/src/main/scala/vinyldns/api/domain/DomainValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/test/functional/tests/batch/create_batch_change_test.py
- modules/api/src/test/scala/vinyldns/api/domain/DomainValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeValidationsSpec.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/DomainValidationErrors.scala
- modules/core/src/main/scala/vinyldns/core/domain/SingleChangeError.scala
Fixes #843.
- Restrict IPV4 address as CNAME in batch changes interface.
> Restrict IPV4 address as CNAME in DNS changes.

- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/test/functional/tests/recordsets/create_recordset_test.py
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetValidationsSpec.scala
Fixes #1181.
**Changes in this pull request:**
- Restrict IPv4 as record data in Cname validation.
> Restrict IPv4 as Cname in manage records

- build/docker/api/application.conf
- modules/api/src/main/resources/application.conf
- modules/api/src/main/resources/reference.conf
- modules/api/src/main/scala/vinyldns/api/Boot.scala
- modules/api/src/main/scala/vinyldns/api/config/ServerConfig.scala
- modules/api/src/test/scala/vinyldns/api/VinylDNSTestHelpers.scala
- modules/api/src/universal/conf/application.conf
- modules/docs/src/main/mdoc/operator/config-api.md
- test/api/functional/application.conf
- test/api/integration/application.conf
Fixes #1232.
- Add a config for zone sync scheduler to perform automated sync only on a single api server/instance instead of being done on all the api servers/instances.
> Add config for zone sync scheduler

- modules/api/src/main/scala/vinyldns/api/backend/dns/DnsBackend.scala
- quickstart/bind9/etc/named.conf.local
Added additional logging to the send method in the DNSBackend class to help with debugging DNS resolver issues.
Example log from local testing:
`DNS Resolver Info: DNS Resolver: SimpleResolver [/127.0.0.1:19001], Resolver Address=/127.0.0.1, Resolver Host=localhost, Resolver Port=19001, Timeout=PT10S"`
> Debug DNS Resolver Info

- modules/portal/public/app.js
- modules/portal/public/lib/controllers/controller.groups.js
- modules/portal/public/lib/controllers/controller.manageZones.js
- modules/portal/public/lib/controllers/controller.membership.js
- modules/portal/public/lib/controllers/controller.records.js
- modules/portal/public/lib/controllers/controller.zones.js
- modules/portal/public/lib/services/utility/service.utility.js
- modules/portal/public/lib/services/zones/service.zones.js
Fixes #1176 
-  Replaced `$log.log` with `$log.debug` to make use of the `$logProvider.debugEnabled()` method to disable portal logs in production and other environments.
> Remove portal logs from browser console

- modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
- modules/api/src/main/scala/vinyldns/api/engine/ZoneChangeHandler.scala
- modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
- modules/portal/app/views/zones/zoneTabs/manageZone.scala.html
- modules/portal/public/lib/controllers/controller.manageZones.js
- Zone change seems to be saved multiple times in the zone change table while performing automated sync. Adding logs to debug. 
- Added a modal to convert the local time entered to it's equivalent UTC time. The modal can be viewed by clicking `Convert to UTC time` below the scheduler.
> Add logs and time converter for automated zone syncs

- build/docker/api/application.conf
- build/docker/api/logback.xml
- build/docker/portal/application.conf
- build/docker/portal/logback.xml
- modules/api/src/main/resources/application.conf
- modules/api/src/main/resources/logback.xml
- modules/api/src/universal/conf/application.conf
- modules/api/src/universal/conf/logback.xml
- modules/portal/conf/application.conf
- modules/portal/conf/logback.xml
- project/Dependencies.scala
Hikari pool stats are now logged on the console. Every 30 seconds the stats get output like this:
`{"@timestamp":"2023-04-26T00:17:26.667Z", "log.level":"DEBUG", "message":"mysqlDbPool - Pool stats (total=10, active=0, idle=10, waiting=0)", "ecs.version": "1.2.0","service.name":"vinyldns-portal","service.node.name":"vinyldns-portal","event.dataset":"vinyldns-portal","process.thread.name":"mysqlDbPool housekeeper","log.logger":"com.zaxxer.hikari.pool.HikariPool"}`
> Enable debug logging for hikariCP

- modules/api/src/main/scala/vinyldns/api/route/DnsJsonProtocol.scala
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/portal/public/css/vinyldns.css
- modules/portal/public/lib/controllers/controller.records.js
- modules/portal/public/templates/record-modal.html
Fixes #1259.
- Added additional validations for NAPTR flags and regexp.
> Add additional NAPTR validations

- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/record/RecordChangeRepository.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlRecordChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordChangeRepository.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
Fixes #1290 .
- Added zone id as a parameter in recordset change failure metrics api.
> added zone id in recordset change failure metrics api parameters

- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/test/functional/tests/recordsets/list_recordset_changes_test.py
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/portal/app/views/recordsets/recordSets.scala.html
- Remove `change history` column from portal and `record change history` route from api to temporarily disallow the feature in PR: https://github.com/vinyldns/vinyldns/pull/1246 until the required database columns `fqdn` and `record type` are populated. Also, new record changes automatically populates the columns `fqdn` and `record type`.
> Temporarily remove record change history

- modules/api/src/main/scala/vinyldns/api/domain/zone/ListZoneChangesResponse.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/zone/ZoneServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/ZoneRoutingSpec.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/ListZoneChangesResults.scala
- modules/core/src/main/scala/vinyldns/core/domain/zone/ZoneChangeRepository.scala
- modules/core/src/test/scala/vinyldns/core/TestZoneData.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneChangeRepositoryIntegrationSpec.scala
- modules/mysql/src/it/scala/vinyldns/mysql/repository/MySqlZoneRepositoryIntegrationSpec.scala
- modules/mysql/src/main/resources/db/migration/V3.30__AddStatusZoneAccess.sql
- modules/mysql/src/main/resources/test/ddl.sql
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/app/views/zones/zones.scala.html
- modules/portal/conf/routes
- modules/portal/public/lib/controllers/controller.manageZones.spec.js
- modules/portal/public/lib/controllers/controller.zones.js
- modules/portal/public/lib/controllers/controller.zones.spec.js
- modules/portal/public/lib/services/zones/service.zones.js
- modules/portal/public/lib/services/zones/service.zones.spec.js
- modules/portal/test/controllers/TestApplicationData.scala
- modules/portal/test/controllers/VinylDNSSpec.scala
- version.sbt
Fixes #617
- Added API for deleted zones history (zones/deleted/changes)
- Made Portal changes to view deleted zones history.
- Removed Cascade from zone_access table. We use this on comparing zone_change table .
- Added zone_status column in zone_access table to identify the deleted zones and used the same in deleting the group.
> list abandoned zones

- modules/api/src/it/scala/vinyldns/api/route53/Route53ApiIntegrationSpec.scala
- modules/r53/src/it/scala/vinyldns/route53/backend/Route53IntegrationSpec.scala
- modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala
- modules/r53/src/main/scala/vinyldns/route53/backend/Route53Credentials.scala
- modules/r53/src/main/scala/vinyldns/route53/backend/Route53ProviderConfig.scala
- project/Dependencies.scala
Refactor route53 to allow assuming a role, either with the default chain, or using a given key pair.
This is the same changes from #1123 but with signed commits.
> refactor: allow assume role with optional externalId

- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- Remove record change history route from api so that no one can access. Previously removed, but was added back by a merge to main branch. This route should not be accessible until record change columns are populated.
> Remove record change history route

- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneProtocol.scala
- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/test/functional/tests/recordsets/get_recordset_test.py
- modules/api/src/test/functional/vinyldns_python.py
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/portal/app/controllers/VinylDNS.scala
- modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
- modules/portal/conf/routes
- modules/portal/public/lib/controllers/controller.records.js
- modules/portal/public/lib/controllers/controller.records.spec.js
- modules/portal/public/lib/services/records/service.records.js
- modules/portal/public/lib/services/records/service.records.spec.js
- modules/portal/test/controllers/VinylDNSSpec.scala
Fixes #1244.
- Added api for record set count and displayed in portal
Steps: 
Login to the vinyldns 
zones > manage records
> Added api for record set count and displayed in portal

- modules/mysql/src/main/resources/db/migration/V3.31__AddZoneChangeFields.sql
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
- modules/portal/app/views/zones/zones.scala.html
- modules/portal/public/lib/controllers/controller.zones.js
- modules/portal/public/lib/services/zones/service.zones.js
Fixes #1330.
- Updated the code from filter the deleted zones in scala to sql query using where conditions to ignore timeout issue.
> updated filter deleted zones using scala to sql query

- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/test/functional/tests/recordsets/list_recordset_changes_test.py
- modules/api/src/test/functional/vinyldns_python.py
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/docs/src/main/mdoc/api/get-recordset-change-history.md
- modules/portal/app/views/recordsets/recordSets.scala.html
- modules/portal/public/lib/recordset/recordsets.controller.js
- modules/portal/public/lib/services/records/service.records.js
Fixes #1337.
- Fixed the column name by making it permanent. 
- Allowed every users to view the history of unowned records.
- For records in the private zones, only the users who belong to the owning group can view the history.
- The button will be disabled if the users don't have the right permissions.
> Fix record change history view in portal

- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipProtocol.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
- modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/MembershipRoutingSpec.scala
Fixes #1334.
- Added group id in user details response API.
> add group id in user response

- modules/core/src/main/scala/vinyldns/core/Messages.scala
- modules/portal/public/lib/dns-change/dns-change-new.controller.js
Fixes #1341
CSV batch change import error message has been improved, there is now an error for the file type and and error for the header being incorrect.
The scala ImportError variable has been removed since it wasn't being used anywhere.
> Improve CSV Import Error Message

- modules/portal/app/views/zones/zones.scala.html
Fixes #1359 .
- Fixed deleted zone `access` issue in portal. Previously, they appeared as `private` even though they were `shared` zones
> fixed deleted zone access issue in portal

- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
Fixes #1360.
- When a record data doesn't exist, updated the case to display the below message:
`The record data entered doesn't exist. Please enter the correct record data or leave the field empty if it's a delete operation.`
> Update info messages

- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetServiceAlgebra.scala
- modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
- modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
- modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordChangeRepository.scala
Fixes #1356.
- Removed the parameters `fqdn` and `recordType` from the `listRecordSetChanges` route as the only parameters in this route are `startFrom` and `maxItems`. The `fqdn` and `recordType` parameters are only used in `listRecordSetChangeHistory` route.
- Reuse `toFqdn` method to save the fqdn to database.
> Remove unnecessary parameters from "listRecordSetChanges"

- quickstart/docker-compose.yml
Fixes #1373 .
- Removed docker compose version since no more use. [Reference](https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313)
-
> Removed docker compose version since no more use

- build/docker/api/logback.xml
- build/docker/portal/logback.xml
- modules/api/src/main/resources/logback.xml
- modules/api/src/universal/conf/logback.xml
- modules/portal/conf/logback.xml
- Update the hikari log level to ERROR so that we only capture and output messages at the ERROR level or higher (FATAL). This makes us easier to debug other issues while only capturing events that may have an impact from hikari side. We can revert back to TRACE level logs when necessary.
> Update Hikari Log Level

- build/docker/api/application.conf
- modules/api/src/it/resources/application.conf
- modules/api/src/main/resources/application.conf
- modules/api/src/universal/conf/application.conf
- modules/docs/src/main/mdoc/operator/config-api.md
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlBatchChangeRepository.scala
- modules/portal/app/models/Meta.scala
- modules/portal/app/views/dnsChanges/dnsChangeNew.scala.html
- modules/portal/public/lib/dns-change/dns-change-new.controller.js
- modules/portal/public/lib/dns-change/dns-change.service.js
- modules/portal/test/models/MetaSpec.scala
- test/api/functional/application.conf
- test/api/integration/application.conf
Fixes #1375.
- Fix for latency issue in batch change upload.
Root Cause:
Since the batch upload will take much time to give response from the SQL side, our akka server gets `503 timeout`, but in backend we gets the successful response.
Fix: 
Increased the akka http timeout to `60seconds` (default is 20s) and keeps the portal in loading state untill we gets the response from api.
> Fix for latency issue in batch change upload

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeConverter.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetChangeGenerator.scala
- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
- modules/api/src/test/functional/vinyldns_python.py
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
- modules/api/src/test/scala/vinyldns/api/engine/RecordSetChangeHandlerSpec.scala
- modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordChangeRepository.scala
Fixes #1388.
- Now when a user submits Add + Delete for a record that already exist with a record data in Delete that doesn't exist, we ignore the Delete and just process the Add to update the record. Which is the ideal behaviour.
Attaching screenshot for reference.
> Fix batch update logic

- modules/portal/public/lib/dns-change/dns-change-detail.controller.js
Fixes #1406 .
- Rearranged the DNS change export csv column
Column order:
Change Type, Record Type, Input Name, TTL, Record Data, Recordset Name, Zone Name, Status, Additional Info
> Rearranged the DNS change export csv column

- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchChangeValidations.scala
- modules/api/src/main/scala/vinyldns/api/domain/batch/BatchTransformations.scala
- modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
- modules/api/src/test/functional/tests/batch/create_batch_change_test.py
- modules/api/src/test/scala/vinyldns/api/domain/batch/BatchChangeConverterSpec.scala
- modules/core/src/main/scala/vinyldns/core/Messages.scala
- When there is a record that exist in Vinyl and we issue a batch change with Delete for that record with a non-existing record data, it throws `out of sync` error. But it should not throw any error and process with info `Record data does not exist. No action is required`. Fixed that in this PR.
> Fix batch delete

- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/test/functional/tests/recordsets/update_recordset_test.py
Bug: as of version 0.21.1, when a user tries to update a record in a private zone from the zone view, it fails with a `422: Cannot update RecordSet OwnerShip Status when zone is not shared.` error.
This can be worked around by updating the record via batch change. Also, once that particular record has been updated via batch change, it can be updated in the zone view as well from then on.
It seems like the issue is that in a private zone, the existing record's recordSetGroupChange is simply set to `None`, whereas the updated record's is set to `Some(OwnerShipTransfer: [ownerShipTransferStatus=\"None\"; requestedOwnerGroupId=\"None\"])`.  This causes the unchangedRecordSetOwnershipStatus check to fail. I have updated the check to pass when the existing record's recordSetGroupChange is set …
> Ownership transfer Bug Fix

- modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetService.scala
- modules/api/src/main/scala/vinyldns/api/domain/record/RecordSetValidations.scala
- modules/api/src/test/functional/tests/recordsets/update_recordset_test.py
Bug: as of version 0.21.1, when a user tries to update a record in a private zone from the zone view, it fails with a `422: Cannot update RecordSet OwnerShip Status when zone is not shared.` error.
This can be worked around by updating the record via batch change. Also, once that particular record has been updated via batch change, it can be updated in the zone view as well from then on.
It seems like the issue is that in a private zone, the existing record's recordSetGroupChange is simply set to `None`, whereas the updated record's is set to `Some(OwnerShipTransfer: [ownerShipTransferStatus=\"None\"; requestedOwnerGroupId=\"None\"])`.  This causes the unchangedRecordSetOwnershipStatus check to fail. I have updated the check to pass when the existing record's recordSetGroupChange is set …
> Ownership transfer bugfix
